#
# Copyright Â© 2005 - 2018 TIBCO Software Inc.
# http://www.jaspersoft.com.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

jsexception.access.denied=Voc\u00ea n\u00e3o tem permiss\u00e3o para realizar a a\u00e7\u00e3o solicitada. Fa\u00e7a login como um usu\u00e1rio com permiss\u00e3o, se for poss\u00edvel.
jsexception.any={0}

jsexception.bean.has.no.method=Bean com o nome {0} n\u00e3o tem m\u00e9todo {1}.
jsexception.bean.name.not.found.for.interface=Nenhum nome de bean foi encontrado para a interface {0}.
jsexception.bean.no.name=N\u00e3o \u00e9 poss\u00edvel encontrar um bean com o nome {0}.
jsexception.bean.not.a.ReportDataSourceService=O bean {0} n\u00e3o \u00e9 ReportDataSourceService.

jsexception.call.not.supported=A chamada n\u00e3o \u00e9 suportada por objetos de pesquisa de recursos.
jsexception.connection.type.not.suported=O tipo de conex\u00e3o n\u00e3o \u00e9 suportado.
jsexception.connection.uri.not.specified=URI de conex\u00e3o n\u00e3o foi especificado.
jsexception.could.not.find.resource.with.uri=O recurso com URI {0} n\u00e3o pode ser encontrado. 
jsexception.could.not.find.content.resource.with.uri=O recurso de conte\u00fado com URI {0} n\u00e3o pode ser encontrado.
jsexception.unexpected.resource.type.at.uri=Tipo inesperado ({0}) do recurso com URI {1} 

jsexception.default.message=Ocorreu um erro inexplicado. Entre em contato com o administrador do sistema.

jsexception.error.creating.connection=Ocorreu um erro durante a cria\u00e7\u00e3o da conex\u00e3o. Tente novamente.
jsexception.parameter.has.multiple.values=Par\u00e2metro {0} tem v\u00e1rios valores.

jsexception.parameter.has.no.value=Par\u00e2metro {0} n\u00e3o tem nenhum valor.


jsexception.failed.to.create.connection=N\u00e3o foi poss\u00edvel criar conex\u00e3o.
jsexception.failed.to.save.connection=A conex\u00e3o n\u00e3o foi salva.
jsexception.failed.to.save.connection.changes=As altera\u00e7\u00f5es de conex\u00e3o n\u00e3o foram salvas.
jsexception.file.resource.is.reference=Recurso do arquivo {0} \u00e9 uma refer\u00eancia e n\u00e3o tem dados.
jsexception.file.resource.no.match.type=O tipo declarado do recurso ({0}) n\u00e3o corresponde ao tipo da refer\u00eancia ({1}).
jsexception.folder.already.exists=J\u00e1 existe uma pasta com o nome {0}. Escolha um nome diferente.
jsexception.folder.details.not.found=Detalhes de pasta {0} n\u00e3o foram encontrados nas informa\u00e7\u00f5es de importa\u00e7\u00e3o. 
jsexception.folder.not.found=A pasta {0} n\u00e3o pode ser encontrada. 
jsexception.folder.not.found.at=A pasta n\u00e3o est\u00e1 em {0}.
jsexception.folder.duplicate.name=J\u00e1 existe uma pasta chamada {0} em {1}.
jsexception.folder.duplicate.label=T\u00edtulo de pasta {0} duplicado na pasta {1}.
jsexception.folder.too.long.uri=O URI da pasta \u00e9 muito longo. O comprimento m\u00e1ximo \u00e9 {0} caracteres.
jsexception.folder.creation.not.allowed={0} \u00e9 um nome reservado e n\u00e3o \u00e9 permitido em {1}.

jsexception.got.null.schema.source.wrapper=O subfluxo retornou um empacotador de fonte de esquema nulo.
jsexception.got.null.access.grant.source.wrapper=O subfluxo retornou um empacotador de fonte de concess\u00e3o de acesso nulo.
jsexception.got.null.connection.back=O subfluxo retornou uma liga\u00e7\u00e3o nula.

jsexception.implementation.class.does.not.implement=Classe de implementa\u00e7\u00e3o {0} n\u00e3o implementa {1}.
jsexception.implementation.class.not.found=Uma classe de implementa\u00e7\u00e3o de {0} n\u00e3o pode ser encontrada.
jsexception.import.directory.not.found=Diret\u00f3rio da importa\u00e7\u00e3o {0} n\u00e3o pode ser encontrado.
jsexception.import.module.not.found=O m\u00f3dulo da importa\u00e7\u00e3o {0} n\u00e3o pode ser encontrado.
jsexception.import.multiple.values.for.single.parameter=V\u00e1rios valores de par\u00e2metro foram encontrados para o par\u00e2metro de valor \u00fanico {0} do relat\u00f3rio {1}.
jsexception.input.stream.exhausted=O fluxo de entrada foi esgotado antes de ler {0} bytes.
jsexception.invalid.bean.datasource=A fonte de dados de bean {0} \u00e9 inv\u00e1lida.
jsexception.invalid.class.attribute.for.model.tag=O atributo de classe para tag do modelo, recurso {0}, \u00e9 inv\u00e1lido.
jsexception.invalid.jdbc.datasource=A fonte de dados de JDBC {0} \u00e9 inv\u00e1lida.
jsexception.invalid.aws.datasource=A fonte de dados AWS {0} \u00e9 inv\u00e1lida.
jsexception.invalid.azureSql.datasource=A fonte de dados do SQL Azure {0} \u00e9 inv\u00e1lida.
jsexception.invalid.jndi.jdbc.datasource=A fonte de dados JNDI JDBC {0} \u00e9 inv\u00e1lida.
jsexception.invalid.olap.datasource=A fonte de dados de OLAP {0} \u00e9 inv\u00e1lida.
jsexception.invalid.resource.reference.source=A fonte de refer\u00eancia {0} do recurso \u00e9 inv\u00e1lido.
jsexception.invalid.session=A sess\u00e3o atual \u00e9 inv\u00e1lida. Verifique se o servidor est\u00e1 em execu\u00e7\u00e3o e tente efetuar login novamente.
jsexception.invalid.uri=URI {0} \u00e9 inv\u00e1lido.

jsexception.jar.entry.not.found=Uma entrada JAR para URL {0} n\u00e3o pode ser encontrada.
jsexception.jar.malformed.url=URL de JAR {0} tem sintaxe incorreta.
jsexception.jasperprint.not.found=O objeto JasperPrint {0} n\u00e3o pode ser encontrado.

jsexception.job.has.more.than.one.trigger=Trabalho {0} tem mais de um acionador.
jsexception.job.no.versions.match=Vers\u00e3o de cliente {0} n\u00e3o \u00e9 a vers\u00e3o mais recente ({1}).
jsexception.job.unknown.calendar.trigger.days.type=Tipo desconhecido de dias do acionador de calend\u00e1rio {0}.
jsexception.job.unknown.interval.unit=Unidade de intervalo de trabalho de relat\u00f3rio desconhecida {0}.
jsexception.job.unknown.start.type=Tipo desconhecido de in\u00edcio de trabalho de relat\u00f3rio {0}.
jsexception.job.unknown.trigger.bean.class=Classe de bean desconhecida do acionador do trabalho de relat\u00f3rio {0}.
jsexception.job.unknown.trigger.type=Tipo desconhecido de acionador do trabalho de relat\u00f3rio {0}.

jsexception.missing.olap.connection=A conex\u00e3o OLAP est\u00e1 ausente.
jsexception.missing.olap.connection.reference=A refer\u00eancia de conex\u00e3o OLAP est\u00e1 ausente.
jsexception.mondrian.jdbc.datasource.has.an.invalid.type=A fonte de dados JDBC da conex\u00e3o Mondrian \u00e9 um tipo inv\u00e1lido ({0}).

jsexception.no.connection.selected=Nenhuma conex\u00e3o selecionada.
jsexception.no.export.folder.specified=Nenhuma pasta de exporta\u00e7\u00e3o especificada.
jsexception.no.export.zip.file.specified=Nenhum arquivo ZIP de exporta\u00e7\u00e3o especificado.
jsexception.no.import.folder.specified=Nenhuma pasta de importa\u00e7\u00e3o especificada.
jsexception.no.import.zip.file.specified=Nenhum arquivo ZIP de importa\u00e7\u00e3o especificado.
jsexception.no.input.parameter.specified=Nenhum par\u00e2metro de entrada especificado.
jsexception.no.olap.client.connection=Nenhuma conex\u00e3o de cliente OLAP encontrada.
jsexception.no.secure.olap.client.connection=Nenhuma conex\u00e3o de cliente OLAP segura encontrada.
jsexception.no.olap.model.created.for=Nenhum modelo OLAP criado para {0}.
jsexception.no.olap.model.name=Nenhum modelo OLAP especificado.
jsexception.no.olap.model.retrieved=Nenhum modelo OLAP pode ser recuperado.
jsexception.no.output.parameter.specified=Nenhum par\u00e2metro de sa\u00edda especificado.
jsexception.no.persistent.class.mapped.to=Nenhuma classe persistente est\u00e1 mapeada para {0}.
jsexception.no.resource.data.provider.found=Nenhum provedor de dados de recurso encontrado para ID {0}.
jsexception.no.such.object.permission=A permiss\u00e3o do objeto especificado n\u00e3o existe.
jsexception.no.such.role=N\u00e3o existe fun\u00e7\u00e3o {0}.
jsexception.no.such.user=N\u00e3o existe usu\u00e1rio {0}.
jsexception.no.uri.or.recipient.given=Nenhum URI ou recipiente especificado.
jsexception.no.values.to.enumerate=Nenhum valor especificado para enumera\u00e7\u00e3o.
jsexception.no.values.to.enumerate={0} n\u00e3o \u00e9 um URI de recurso v\u00e1lido.
jsexception.null.uri=URI nulo.

jsexception.output.stream.already.closed=O fluxo de sa\u00edda j\u00e1 est\u00e1 fechado.

jsexception.property.not.a.list=Propriedade {0} do bean {1} n\u00e3o \u00e9 uma propriedade de lista.
jsexception.property.not.a.map=Propriedade {0} do bean {1} n\u00e3o \u00e9 uma propriedade de mapa.
jsexception.property.not.a.text=Propriedade {0} do bean {1} n\u00e3o \u00e9 uma propriedade de texto.

jsexception.query.datasource.has.an.invalid.type=A fonte de dados de consulta tem um tipo inv\u00e1lido ({0}).

jsexception.report.job.not.found=Um trabalho de relat\u00f3rio com ID {0} n\u00e3o pode ser encontrado.
jsexception.report.resource.already.exists.no.overwrite=Recurso de sa\u00edda {0} j\u00e1 existe e a bandeira de substitui\u00e7\u00e3o do trabalho n\u00e3o est\u00e1 definida.
jsexception.report.no.content.resource=Recurso {0} n\u00e3o \u00e9 um recurso de conte\u00fado.
jsexception.report.unit.datasource.has.an.invalid.type=A fonte de dados de unidade de relat\u00f3rio tem um tipo inv\u00e1lido ({0}).
jsexception.report.unknown.output.format=Formato de sa\u00edda do relat\u00f3rio {0} n\u00e3o \u00e9 um formato conhecido.
jsexception.repository.uri.neither.report.nor.folder=O URI do reposit\u00f3rio {0} n\u00e3o \u00e9 uma unidade de relat\u00f3rio nem uma pasta.
jsexception.resource.already.exists=Recurso {0} j\u00e1 existe. Escolha um nome diferente.
jsexception.resource.copyTo.not.implemented=copyTo do recurso n\u00e3o est\u00e1 implementado.
jsexception.resource.copyFrom.not.implemented=copyFrom do recurso n\u00e3o est\u00e1 implementado.
jsexception.resource.does.not.exist=Recurso {0} n\u00e3o existe.
jsexception.resource.no.match.versions={0}: cliente vers\u00e3o {1} n\u00e3o corresponde \u00e0 vers\u00e3o do reposit\u00f3rio ({2}).
jsexception.resource.of.type.not.found=Recurso {0} do tipo {1} n\u00e3o pode ser encontrado.
jsexception.resource.not.report.unit=Recurso {0} n\u00e3o \u00e9 uma unidade de relat\u00f3rio.
jsexception.resourcelookup.not.a.resource=ResourceLookup n\u00e3o \u00e9 um recurso: {0}.
jsexception.folder.delete.root=A pasta raiz n\u00e3o pode ser exclu\u00edda.
jsexception.report.template.not.found=O URI do reposit\u00f3rio {0} n\u00e3o \u00e9 um modelo de relat\u00f3rio.
jsexception.report.template.uri.not.specified=URI de modelo n\u00e3o foi especificado.

jsexception.selected.report.not.adhoc=O relat\u00f3rio selecionado n\u00e3o \u00e9 um relat\u00f3rio Ad Hoc. Unidades de relat\u00f3rios regulares n\u00e3o s\u00e3o suportadas.
jsexception.session.timeout.occurred=A sess\u00e3o de OLAP expirou.

jsexception.too.many.data.rows=O exportador do Excel falhou devido ao excesso de linhas de dados. Voc\u00ea pode alterar as configura\u00e7\u00f5es do exportador para uma p\u00e1gina por folha.

jsexception.unable.to.complete.request=O sistema n\u00e3o conseguiu concluir sua solicita\u00e7\u00e3o. Sua conversa terminou, expirou, ou foi invalidada.
jsexception.undefined.file.type=O tipo de arquivo n\u00e3o \u00e9 reconhecido.
jsexception.unknown.connection.type=O tipo de conex\u00e3o n\u00e3o foi reconhecido.
jsexception.unknown.parameter.type.for.multiple.value.input=O tipo de par\u00e2metro {0} n\u00e3o \u00e9 v\u00e1lido para a entrada de v\u00e1rios valores.
jsexception.unknown.permission.recipient.type=Tipo de recipiente de permiss\u00e3o {0} n\u00e3o \u00e9 reconhecido.
jsexception.unknown.property.filter.operation=Opera\u00e7\u00e3o do filtro de propriedade {0} n\u00e3o \u00e9 reconhecida.
jsexception.unknown.timezone=Fuso hor\u00e1rio {0} n\u00e3o \u00e9 reconhecido. 
jsexception.uri.not.found=URI {0} n\u00e3o pode ser encontrado no reposit\u00f3rio.
jsexception.user.credentials.are.expired=Credenciais do usu\u00e1rio {0} expiraram.
jsexception.user.disabled=Usu\u00e1rio {0} est\u00e1 desativado.
jsexception.user.expired=Usu\u00e1rio {0} expirou.
jsexception.user.locked=Usu\u00e1rio {0} est\u00e1 bloqueado.
jsexception.user.not.found=Usu\u00e1rio {0} n\u00e3o pode ser encontrado.

jsexception.move.folder.source.uri.ancestor.destination={0} n\u00e3o pode ser movido para {1}. O destino \u00e9 um filho da fonte.
jsexception.move.folder.to.same.folder=N\u00e3o \u00e9 poss\u00edvel mover pasta {0} para a mesma pasta {1}.
jsexception.move.resource.to.same.folder=N\u00e3o \u00e9 poss\u00edvel mover recurso {0} para a mesma pasta {1}.
jsexception.move.folder.path.already.exists=N\u00e3o \u00e9 poss\u00edvel mover pasta {0} para {1}. A pasta de destino j\u00e1 cont\u00e9m um objeto com o mesmo nome.
jsexception.move.resource.path.already.exists=N\u00e3o \u00e9 poss\u00edvel mover recurso {0} para {1}. O destino j\u00e1 cont\u00e9m um objeto com o mesmo nome.
jsexception.copy.resource.referenced.not.readable=Recurso {0} \u00e9 referenciado por outro recurso, mas n\u00e3o \u00e9 leg\u00edvel.
jsexception.copy.resource.circular.reference=Foi detectada um refer\u00eancia circular para recurso {0}.
jsexception.folder.moved=Pasta {0} foi movida para {1}.

report.scheduling.error.filling.report=O relat\u00f3rio n\u00e3o foi conclu\u00eddo. Ocorreu um erro ao execut\u00e1-lo.
report.scheduling.error.exporting.report=Exporta\u00e7\u00e3o para {0} n\u00e3o foi conclu\u00edda. Um erro interrompeu o processo.
report.scheduling.error.saving.to.repository={0} n\u00e3o foi salvo em um reposit\u00f3rio. Um erro interrompeu o processo.
report.scheduling.error.sending.email.notification=A notifica\u00e7\u00e3o de erro de trabalho n\u00e3o foi conclu\u00edda. Ocorreu um erro durante o envio.
report.scheduling.error.system=O trabalho n\u00e3o foi conclu\u00eddo. Ocorreu um erro do sistema ao execut\u00e1-lo.

exception.report.unrecognized.number.type=Tipo num\u00e9rico desconhecido {0}
exception.report.unrecognized.date.type=Tipo de data/hora desconhecido {0}
exception.report.unsupported.date.input.value=N\u00e3o \u00e9 poss\u00edvel converter o valor de entrada {0} do tipo {1} para um par\u00e2metro de data/hora.
exception.report.unsupported.date.parameter.type=Tipo de data/hora n\u00e3o suportado {0}
exception.report.unsupported.input.control.data.type=Tipo de dados da entrada de controle {0} n\u00e3o \u00e9 suportado.

jsexception.view.report.could.not.load=A unidade do relat\u00f3rio n\u00e3o pode ser encontrada ou n\u00e3o pode ser carregada.
jsexception.view.page.does.not.exist=P\u00e1gina {0} n\u00e3o encontrada no relat\u00f3rio
jsexception.view.report.error=Ocorreu um erro durante a gera\u00e7\u00e3o do relat\u00f3rio
jsexception.export.unknown.argument=Op\u00e7\u00e3o {0} n\u00e3o \u00e9 reconhecida.

jsexception.mondrian.no.connection.for.resource=N\u00e3o existe conex\u00e3o Mondrian para recurso {0}.

jsexception.target.org.not.found=Organiza\u00e7\u00e3o alvo {0} n\u00e3o pode ser encontrada no reposit\u00f3rio.
jsexception.template.folder.not.found=N\u00e3o foi poss\u00edvel localizar a pasta de modelos no reposit\u00f3rio.

jsexception.search.duplicate.label=J\u00e1 existe um objeto com o t\u00edtulo {0} na pasta {1}.
jsexception.search.duplicate.name=J\u00e1 existe um objeto com o nome {0} na pasta {1}.

report.scheduling.error.saving.data.snapshot.disabled=Grava\u00e7\u00e3o de instant\u00e2neo de dados desativada.
report.scheduling.error.data.snapshot.not.populated=Instant\u00e2neo de dados n\u00e3o foi preenchido.
report.scheduling.error.data.snapshot.not.persistable=Instant\u00e2neo de dados n\u00e3o pode ser salvo.
report.scheduling.error.saving.data.snapshot.failed=Erro ao salvar instant\u00e2neo de dados.

exception.remote.resource.already.exists=Recurso {0} j\u00e1 existe.
exception.remote.resource.not.found=Recurso {0} n\u00e3o encontrado.
exception.remote.resource.type.not.supported=Tipo de recurso {0} n\u00e3o \u00e9 suportado por esta opera\u00e7\u00e3o.
exception.remote.folder.not.found=Pasta {0} n\u00e3o foi encontrada ou n\u00e3o \u00e9 uma pasta.
exception.remote.unexpected.error=Erro inesperado.
exception.remote.weak.password=Senha fraca.
exception.remote.attribute.permission.order.invalid=A permiss\u00e3o de atributo para {0} n\u00e3o pode ser modificada para uma permiss\u00e3o mais r\u00edgida {1}. Escolha uma permiss\u00e3o que seja mais restritiva ou igual \u00e0 permiss\u00e3o herdada {2}.
exception.remote.attribute.permission.recipient.invalid=O destinat\u00e1rio da permiss\u00e3o de atributo {0} para {1} \u00e9 inv\u00e1lido.
exception.remote.resource.not.ready=Tarefa {0} ainda n\u00e3o terminada.
exception.remote.no.such.export.process=Nenhuma tarefa de exporta\u00e7\u00e3o com id {0}.
exception.remote.no.such.import.process=Nenhuma tarefa de importa\u00e7\u00e3o com id {0}.
exception.remote.access.denied=Acesso negado.
exception.remote.modification.not.allowed=Modifica\u00e7\u00e3o do recurso {0} n\u00e3o \u00e9 permitida.
exception.remote.illegal.parameter.value.error=Valor do par\u00e2metro "{1}" do par\u00e2metro "{0}" \u00e9 inv\u00e1lido.
exception.remote.invalid.query.structure.error=A consulta deve conter pelo menos uma cl\u00e1usula n\u00e3o vazia: selecionar ou groupBy.
exception.remote.invalid.query.reference.integrity.error=A consulta falhou ou tem refer\u00eancias inapropriadas aos campos de consulta.
exception.remote.invalid.query.filter.reference.class.error=O filtro faz refer\u00eancia ao campo {0} com tipo n\u00e3o compat\u00edvel {1}
exception.remote.invalid.query.order.generic.reference.class.error=A instru\u00e7\u00e3o de ordem faz refer\u00eancia ao campo {0} do tipo n\u00e3o compat\u00edvel {1}
exception.remote.invalid.query.order.header.null.reference.error=A instru\u00e7\u00e3o de ordem do cabe\u00e7alho n\u00e3o tem refer\u00eancia a n\u00edvel de consulta.
exception.remote.invalid.query.order.header.reference.class.error=A instru\u00e7\u00e3o de ordem do cabe\u00e7alho faz refer\u00eancia ao campo {0} do tipo n\u00e3o compat\u00edvel {1}
exception.remote.invalid.query.expansion.header.null.reference.error=A instru\u00e7\u00e3o de expans\u00e3o do cabe\u00e7alho n\u00e3o tem refer\u00eancia a n\u00edvel de consulta.
exception.remote.invalid.query.expansion.level.reference.class.error=A instru\u00e7\u00e3o de expans\u00e3o do cabe\u00e7alho faz refer\u00eancia ao campo {0} do tipo n\u00e3o compat\u00edvel {1}
exception.remote.invalid.query.expansion.level.ambiguous.reference.error=A expans\u00e3o do cabe\u00e7alho faz refer\u00eancia a um campo que n\u00e3o \u00e9 exclusivamente identific\u00e1vel {0}.
exception.remote.invalid.query.aggregated.field.reference.class.error=A instru\u00e7\u00e3o de expans\u00e3o do cabe\u00e7alho faz refer\u00eancia ao campo {0} do tipo n\u00e3o compat\u00edvel {1}
exception.remote.mandatory.parameter.error=Par\u00e2metro obrigat\u00f3rio "{0}" est\u00e1 ausente.
exception.remote.mandatory.olap.parameter.select.aggregations.error=O par\u00e2metro obrigat\u00f3rio "select.aggregations" est\u00e1 ausente.
exception.remote.mandatory.olap.parameter.groupBy.columns.error=O par\u00e2metro obrigat\u00f3rio "groupBy.columns" est\u00e1 ausente.
exception.remote.mandatory.olap.parameter.groupBy.aggregations.error=O par\u00e2metro obrigat\u00f3rio "agrega\u00e7\u00f5es" para "groupBy.columns" ou "groupBy.rows" est\u00e1 ausente.
exception.remote.parameter.groupBy.multiple.aggregations.error=Foram encontrados v\u00e1rios par\u00e2metros de "agrega\u00e7\u00f5es". Somente um par\u00e2metro \u00e9 permitido para "groupBy.columns" ou "groupBy.rows".
exception.remote.import.failed=Falha na importa\u00e7\u00e3o. Motivo: {0}
exception.remote.import.failed.zip.error=Falha na importa\u00e7\u00e3o. Motivo: n\u00e3o \u00e9 poss\u00edvel ler o arquivo zip.
exception.remote.import.failed.content.error=Falha na importa\u00e7\u00e3o. Motivo: arquivo zip fornecido n\u00e3o \u00e9 arquivo de exporta\u00e7\u00e3o de Jasper Server v\u00e1lido.
exception.remote.resource.querying.not.supported=Recurso {0} n\u00e3o tem suporte para consultas
exception.remote.version.not.match=Falha na atualiza\u00e7\u00e3o: vers\u00f5es n\u00e3o correspondem
exception.remote.query.datasource.type.not.supported=A fonte de dados da consulta "{0}" n\u00e3o \u00e9 suportada.
exception.remote.query.datasource.olap.view.not.supported=A fonte de dados da consulta "{0}", com base no Olap View, n\u00e3o \u00e9 suportada.
exception.remote.parameter.name.not.valid=O nome do par\u00e2metro \u00e9 inv\u00e1lido. O nome deve come\u00e7ar com o caractere alfab\u00e9tico e permitir apenas A-z_e n\u00fameros.

exception.remote.aggregate.expression.is.not.valid=A express\u00e3o de agrega\u00e7\u00e3o "{1}" para o campo "{0}" n\u00e3o \u00e9 v\u00e1lida.
exception.remote.query.datasource.not.found="Fonte de dados da consulta "{0}" n\u00e3o encontrada "
exception.remote.query.datasource.access.denied=Acesso negado para a fonte de dados da consulta "{0}"
exception.remote.query.level.hierarchy.not.valid=Os n\u00edveis de uma dimens\u00e3o t\u00eam hierarquia diferente. Somente os n\u00edveis de uma \u00fanica hierarquia podem ser selecionados.
exception.remote.olap.query.limit.not.supported=O limite de consulta n\u00e3o \u00e9 suportado para OLAP.
exception.remote.paging.params.axes.count.out.of.bound=A contagem dos eixos dos par\u00e2metros de pagina\u00e7\u00e3o n\u00e3o deve ser maior que {0}.
exception.remote.query.fields.from.multiple.dataislands=Os campos de consulta {0} e {1} s\u00e3o de v\u00e1rias ilhas de dados.
exception.remote.query.aggregate.definition.error=A defini\u00e7\u00e3o de agrega\u00e7\u00e3o n\u00e3o pode ter a fun\u00e7\u00e3o e a express\u00e3o de agrega\u00e7\u00e3o.
exception.remote.query.calculated.field.expression.missing=Express\u00e3o de campo calculado ausente.
exception.remote.path.list.not.valid=O segmento do caminho cont\u00e9m caracteres inv\u00e1lidos
exception.remote.query.field.id.collision=A ID do campo de consulta est\u00e1 em conflito com alguma ID do campo de consulta existente ou com um nome de campo da fonte de dados.
exception.remote.query.parameter.name.query.field.id.collision=O nome do par\u00e2metro de consulta "{0}" est\u00e1 em conflito com uma ID do campo de consulta existente.
exception.remote.query.parameter.name.metadata.field.collision=O nome do par\u00e2metro de consulta "{0}" est\u00e1 em conflito com o campo de metadados.
exception.remote.query.where.expression.not.valid=A consulta em que a express\u00e3o n\u00e3o \u00e9 v\u00e1lida.
exception.remote.query.calculated.field.expression.not.valid=A express\u00e3o do campo calculado da consulta n\u00e3o \u00e9 v\u00e1lida.
exception.remote.query.aggregation.expression.not.valid=A express\u00e3o de agrega\u00e7\u00e3o da consulta n\u00e3o \u00e9 v\u00e1lida.
exception.remote.query.groupBy.allGroup.not.first=AllGroup deve ser o primeiro.
exception.remote.query.order.generic.fieldReference.not.valid=A Ordem de consulta deve conter fieldRef ou um sinalizador de agrega\u00e7\u00f5es.
exception.remote.query.groupBy.categorizer.not.valid=N\u00e3o \u00e9 poss\u00edvel encontrar o categorizador com este nome {0}.
exception.remote.query.orderBy.topOrBottom.limit.not.valid=O limite n\u00e3o pode ser inferior a 1, mas, na verdade, \u00e9 {1}
exception.remote.query.multiAxis.aggregation.is.empty=A agrega\u00e7\u00e3o da consulta com v\u00e1rios eixos n\u00e3o pode estar vazia.
exception.remote.timezone.is.not.valid=O fuso hor\u00e1rio {0} n\u00e3o \u00e9 v\u00e1lido.

#AWS data source specific exception messages
aws.exception.datasource.recovery.base=Ocorreu uma exce\u00e7\u00e3o durante a recupera\u00e7\u00e3o da fonte de dados AWS: {0}.
aws.exception.datasource.recovery.timeout=Pode haver um problema com a URL de JDBC, Configura\u00e7\u00f5es de Seguran\u00e7a de AWS ou o processo de recupera\u00e7\u00e3o de Fonte de dados AWS, que pode levar at\u00e9 2 minutos.
aws.exception.datasource.recovery.instance.not.active=A inst\u00e2ncia de fonte de dados AWS n\u00e3o est\u00e1 ativa.
aws.exception.datasource.recovery.is.not.possible=A fonte de dados AWS n\u00e3o pode ser recuperada automaticamente, pois seu JasperReports Server e a inst\u00e2ncia de banco de dados n\u00e3o est\u00e3o localizados no mesmo VPC.
aws.exception.datasource.recovery.public.ip.not.provided=Voc\u00ea deve fornecer o 'IP P\u00fablico de Ingresso' deste servidor nas Configura\u00e7\u00f5es em Nuvem para usar a configura\u00e7\u00e3o e recupera\u00e7\u00e3o autom\u00e1tica da Fonte de dados AWS.
aws.exception.datasource.recovery.public.ip.not.determined=N\u00e3o foi poss\u00edvel determinar o endere\u00e7o IP da inst\u00e2ncia para a recupera\u00e7\u00e3o de Fonte de Dados AWS.
aws.exception.datasource.load.default.credentials=Essa inst\u00e2ncia n\u00e3o pode usar <b>credenciais da inst\u00e2ncia EC2</b> para se conectar automaticamente a Amazon RDS e Amazon Redshift, porque n\u00e3o tem atribu\u00edda uma Fun\u00e7\u00e3o de Gerenciamento de Acesso e Identidade (Identity and Access Management - IAM). Leia <a class='launcher inline' href='http://community.jaspersoft.com/jaspersoft-aws/launch' target='_blank'>Como Iniciar Jaspersoft para AWS</a> para aprender como iniciar um servidor que pode conectar automaticamente e com seguran\u00e7a a fontes de dados AWS.<br><br>Como alternativa voc\u00ea pode usar <b>credenciais AWS</b>.
aws.exception.datasource.rds.vpc.recovery=N\u00e3o \u00e9 poss\u00edvel atribuir automaticamente o grupo de seguran\u00e7a VPC chamado {0} a inst\u00e2ncia de RDS {1}. A opera\u00e7\u00e3o n\u00e3o \u00e9 suportada por AWS API atualmente. Por favor atribuir manualmente o grupo de seguran\u00e7a para sua inst\u00e2ncia de RDS.
aws.exception.datasource.accessKey.invalid=Chave de acesso AWS \u00e9 inv\u00e1lida.
aws.exception.datasource.secretKey.invalid=Chave secreta AWS \u00e9 inv\u00e1lida.

#AZURE data source specific exception messages
azure.exception.datasource.recovery.public.ip.not.provided=Voc\u00ea deve fornecer o 'IP P\u00fablico de Ingresso' deste servidor nas Configura\u00e7\u00f5es em Nuvem para usar a configura\u00e7\u00e3o e recupera\u00e7\u00e3o autom\u00e1tica de Fonte de dados do Azure.
azure.exception.datasource.recovery.firewall.rule.name.not.provided=Voc\u00ea deve fornecer o 'Nome da Regra de Firewall' deste servidor nas Configura\u00e7\u00f5es em Nuvem para usar a configura\u00e7\u00e3o e recupera\u00e7\u00e3o autom\u00e1tica da Fonte de dados do Azure.
azure.exception.datasource.recovery.server.name.not.provided=Voc\u00ea deve fornecer o 'Nome do Servidor' deste servidor para usar a configura\u00e7\u00e3o e recupera\u00e7\u00e3o autom\u00e1tica da Fonte de Dados do Azure.
azure.exception.datasource.recovery.subscription.id.not.provided=Voc\u00ea deve fornecer a 'ID de Assinatura' para usar a configura\u00e7\u00e3o e recupera\u00e7\u00e3o autom\u00e1tica do Banco de Dados do Azure.
azure.exception.datasource.recovery.key.store.file.not.provided=Voc\u00ea deve fornecer o 'Arquivo de Armazenamento Principal' para usar a configura\u00e7\u00e3o e recupera\u00e7\u00e3o autom\u00e1tica do Banco de Dados do Azure.
azure.exception.datasource.recovery.key.store.type.not.provided=Voc\u00ea deve fornecer o 'Tipo de Armazenamento Principal' para usar a configura\u00e7\u00e3o e recupera\u00e7\u00e3o do Banco de Dados do Azure automatizadas.
azure.exception.datasource.key.error=Erro ao ler o arquivo de certificado do reposit\u00f3rio. Verifique se o arquivo de certificado e a senha s\u00e3o v\u00e1lidos.
azure.exception.datasource.auth.error=Erro de autentica\u00e7\u00e3o. Verifique se a ID de assinatura e o certificado s\u00e3o v\u00e1lidos.
azure.exception.datasource.cannot.retrieve.database.list=N\u00e3o foi poss\u00edvel recuperar os bancos de dados do gerenciamento de SQL.
azure.exception.datasource.cannot.ensure.firewall.rule=N\u00e3o foi poss\u00edvel garantir a regra de firewall do Azure.
azure.exception.datasource.cannot.recover.datasource=N\u00e3o foi poss\u00edvel recuperar o Banco de Dados do Azure

#Cluster specific exception messages
cluster.exception.session.attribute.missing=Um erro n\u00e3o relacionado ocorreu no servidor. Sua sess\u00e3o foi reiniciada, mas o trabalho n\u00e3o salvo foi perdido. Por favor, desculpe o transtorno.<p><p>Clique no link abaixo para voltar para a p\u00e1gina inicial e recome\u00e7ar: <a class="launcher inline" href="home.html">Ir \u00e0 p\u00e1gina inicial</a>. Se encontrar outro erro, entre em contato com o administrador.
cluster.exception.session.attribute.missing.popup=Um erro n\u00e3o relacionado ocorreu no servidor. Sua sess\u00e3o foi reiniciada, mas o trabalho n\u00e3o salvo foi perdido. Por favor, desculpe o transtorno.<p><p>Clique no bot\u00e3o abaixo para voltar para a p\u00e1gina inicial e recome\u00e7ar. Se encontrar outro erro, entre em contato com o administrador.

#Profile attributes substitution error and debug level messages
profile.attribute.exception.substitution.base = Erro de substitui\u00e7\u00e3o no recurso {0}, campo {1}.
profile.attribute.exception.substitution.not.found = O atributo {0} n\u00e3o foi definido em {1}.
profile.attribute.exception.substitution.category.invalid = A categoria {0} do atributo {1} n\u00e3o corresponde ao esperado {2} esperado.
profile.attribute.debug.substitution.success = O atributo {0} substitu\u00eddo no recurso {1}. Novo {2} valor de campo: {3}.

#Query execution exceptions.
query.execution.not.found=Execu\u00e7\u00e3o da consulta {0} n\u00e3o encontrada

#Paging exceptions.
paging.offset.out.of.range = O desvio especificado \u00e9 inv\u00e1lido. O desvio deve ser limitado por {0} e {1}.
paging.page.size.out.of.range = O tamanho de p\u00e1gina especificado \u00e9 inv\u00e1lido. O tamanho de p\u00e1gina deve ser delimitado por {0} e {1}.
query.limit.out.of.range = O limite de consultas especificado \u00e9 inv\u00e1lido. O limite de consultas deve ser limitado por {0} e {1}.

# Ad Hoc REST
query.details.unsupported=As consultas com v\u00e1rios eixos n\u00e3o suportam os detalhes.
query.where.parameter.not.valid=O par\u00e2metro "{0}" tem um valor inv\u00e1lido "{1}" para o operador "{2}".
query.field.id.collision=A ID do campo de consulta "{0}" est\u00e1 em conflito com alguma ID do campo de consulta existente.
query.field.id.metadata.field.collision=A ID do campo de consulta "{0}" est\u00e1 em conflito com o nome do campo de metadados.
query.parameter.name.query.field.id.collision=O nome do par\u00e2metro de consulta "{0}" est\u00e1 em conflito com uma ID do campo de consulta existente.
query.parameter.name.metadata.field.collision=O nome do par\u00e2metro de consulta "{0}" est\u00e1 em conflito com o campo de metadados.
report.missing.data.source.fields=O relat\u00f3rio cont\u00e9m um ou mais itens que n\u00e3o est\u00e3o nos dados de origem. Voc\u00ea deve editar a exibi\u00e7\u00e3o Ad Hoc usada para criar este relat\u00f3rio e salv\u00e1-lo novamente.
adhoc.missing.data.source.fields=A exibi\u00e7\u00e3o cont\u00e9m um ou mais itens que n\u00e3o est\u00e3o nos dados de origem. Voc\u00ea deve editar a exibi\u00e7\u00e3o Ad Hoc.
