#
# Copyright (C) 2005 - 2019 TIBCO Software Inc. All rights reserved.
# http://www.jaspersoft.com.
#
# Unless you have purchased a commercial license agreement from Jaspersoft,
# the following license terms apply:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

jsexception.access.denied=Voc\u00EA n\u00E3o tem permiss\u00E3o para realizar a a\u00E7\u00E3o solicitada. Fa\u00E7a login como um usu\u00E1rio com permiss\u00E3o, se for poss\u00EDvel.
jsexception.any={0}

jsexception.bean.has.no.method=Bean com o nome {0} n\u00E3o tem m\u00E9todo {1}.
jsexception.bean.name.not.found.for.interface=Nenhum nome de bean foi encontrado para a interface {0}.
jsexception.bean.no.name=N\u00E3o \u00E9 poss\u00EDvel encontrar um bean com o nome {0}.
jsexception.bean.not.a.ReportDataSourceService=O bean {0} n\u00E3o \u00E9 ReportDataSourceService.

jsexception.call.not.supported=A chamada n\u00E3o \u00E9 suportada por objetos de pesquisa de recursos.
jsexception.connection.type.not.suported=O tipo de conex\u00E3o n\u00E3o \u00E9 suportado.
jsexception.connection.uri.not.specified=URI de conex\u00E3o n\u00E3o foi especificado.
jsexception.could.not.find.resource.with.uri=O recurso com URI {0} n\u00E3o pode ser encontrado. 
jsexception.could.not.find.content.resource.with.uri=O recurso de conte\u00FAdo com URI {0} n\u00E3o pode ser encontrado.
jsexception.unexpected.resource.type.at.uri=Tipo inesperado ({0}) do recurso com URI {1} 

jsexception.default.message=Ocorreu um erro inexplicado. Entre em contato com o administrador do sistema.

jsexception.error.creating.connection=Ocorreu um erro durante a cria\u00E7\u00E3o da conex\u00E3o. Tente novamente.
jsexception.parameter.has.multiple.values=Par\u00E2metro {0} tem v\u00E1rios valores.

jsexception.parameter.has.no.value=Par\u00E2metro {0} n\u00E3o tem nenhum valor.


jsexception.failed.to.create.connection=N\u00E3o foi poss\u00EDvel criar conex\u00E3o.
jsexception.failed.to.save.connection=A conex\u00E3o n\u00E3o foi salva.
jsexception.failed.to.save.connection.changes=As altera\u00E7\u00F5es de conex\u00E3o n\u00E3o foram salvas.
jsexception.file.resource.is.reference=Recurso do arquivo {0} \u00E9 uma refer\u00EAncia e n\u00E3o tem dados.
jsexception.file.resource.no.match.type=O tipo declarado do recurso ({0}) n\u00E3o corresponde ao tipo da refer\u00EAncia ({1}).
jsexception.folder.already.exists=J\u00E1 existe uma pasta com o nome {0}. Escolha um nome diferente.
jsexception.folder.details.not.found=Detalhes de pasta {0} n\u00E3o foram encontrados nas informa\u00E7\u00F5es de importa\u00E7\u00E3o. 
jsexception.folder.not.found=A pasta {0} n\u00E3o pode ser encontrada. 
jsexception.folder.not.found.at=A pasta n\u00E3o est\u00E1 em {0}.
jsexception.folder.duplicate.name=J\u00E1 existe uma pasta chamada {0} em {1}.
jsexception.folder.duplicate.label=T\u00EDtulo de pasta {0} duplicado na pasta {1}.
jsexception.folder.too.long.uri=O URI da pasta \u00E9 muito longo. O comprimento m\u00E1ximo \u00E9 {0} caracteres.
jsexception.folder.creation.not.allowed={0} \u00E9 um nome reservado e n\u00E3o \u00E9 permitido em {1}.

jsexception.got.null.schema.source.wrapper=O subfluxo retornou um empacotador de fonte de esquema nulo.
jsexception.got.null.access.grant.source.wrapper=O subfluxo retornou um empacotador de fonte de concess\u00E3o de acesso nulo.
jsexception.got.null.connection.back=O subfluxo retornou uma liga\u00E7\u00E3o nula.

jsexception.implementation.class.does.not.implement=Classe de implementa\u00E7\u00E3o {0} n\u00E3o implementa {1}.
jsexception.implementation.class.not.found=Uma classe de implementa\u00E7\u00E3o de {0} n\u00E3o pode ser encontrada.
jsexception.import.directory.not.found=Diret\u00F3rio da importa\u00E7\u00E3o {0} n\u00E3o pode ser encontrado.
jsexception.import.module.not.found=O m\u00F3dulo da importa\u00E7\u00E3o {0} n\u00E3o pode ser encontrado.
jsexception.import.multiple.values.for.single.parameter=V\u00E1rios valores de par\u00E2metro foram encontrados para o par\u00E2metro de valor \u00FAnico {0} do relat\u00F3rio {1}.
jsexception.input.stream.exhausted=O fluxo de entrada foi esgotado antes de ler {0} bytes.
jsexception.invalid.bean.datasource=A fonte de dados de bean {0} \u00E9 inv\u00E1lida.
jsexception.invalid.class.attribute.for.model.tag=O atributo de classe para tag do modelo, recurso {0}, \u00E9 inv\u00E1lido.
jsexception.invalid.jdbc.datasource=A fonte de dados de JDBC {0} \u00E9 inv\u00E1lida.
jsexception.invalid.aws.datasource=A fonte de dados AWS {0} \u00E9 inv\u00E1lida.
jsexception.invalid.azureSql.datasource=A fonte de dados do SQL Azure {0} \u00E9 inv\u00E1lida.
jsexception.invalid.jndi.jdbc.datasource=A fonte de dados JNDI JDBC {0} \u00E9 inv\u00E1lida.
jsexception.invalid.olap.datasource=A fonte de dados de OLAP {0} \u00E9 inv\u00E1lida.
jsexception.invalid.resource.reference.source=A fonte de refer\u00EAncia {0} do recurso \u00E9 inv\u00E1lido.
jsexception.invalid.session=A sess\u00E3o atual \u00E9 inv\u00E1lida. Verifique se o servidor est\u00E1 em execu\u00E7\u00E3o e tente efetuar login novamente.
jsexception.invalid.uri=URI {0} \u00E9 inv\u00E1lido.

jsexception.jar.entry.not.found=Uma entrada JAR para URL {0} n\u00E3o pode ser encontrada.
jsexception.jar.malformed.url=URL de JAR {0} tem sintaxe incorreta.
jsexception.jasperprint.not.found=O objeto JasperPrint {0} n\u00E3o pode ser encontrado.

jsexception.job.has.more.than.one.trigger=Trabalho {0} tem mais de um acionador.
jsexception.job.no.versions.match=Vers\u00E3o de cliente {0} n\u00E3o \u00E9 a vers\u00E3o mais recente ({1}).
jsexception.job.unknown.calendar.trigger.days.type=Tipo desconhecido de dias do acionador de calend\u00E1rio {0}.
jsexception.job.unknown.interval.unit=Unidade de intervalo de trabalho de relat\u00F3rio desconhecida {0}.
jsexception.job.unknown.start.type=Tipo desconhecido de in\u00EDcio de trabalho de relat\u00F3rio {0}.
jsexception.job.unknown.trigger.bean.class=Classe de bean desconhecida do acionador do trabalho de relat\u00F3rio {0}.
jsexception.job.unknown.trigger.type=Tipo desconhecido de acionador do trabalho de relat\u00F3rio {0}.

jsexception.missing.olap.connection=A conex\u00E3o OLAP est\u00E1 ausente.
jsexception.missing.olap.connection.reference=A refer\u00EAncia de conex\u00E3o OLAP est\u00E1 ausente.
jsexception.mondrian.jdbc.datasource.has.an.invalid.type=A fonte de dados JDBC da conex\u00E3o Mondrian \u00E9 um tipo inv\u00E1lido ({0}).

jsexception.no.connection.selected=Nenhuma conex\u00E3o selecionada.
jsexception.no.export.folder.specified=Nenhuma pasta de exporta\u00E7\u00E3o especificada.
jsexception.no.export.zip.file.specified=Nenhum arquivo ZIP de exporta\u00E7\u00E3o especificado.
jsexception.no.import.folder.specified=Nenhuma pasta de importa\u00E7\u00E3o especificada.
jsexception.no.import.zip.file.specified=Nenhum arquivo ZIP de importa\u00E7\u00E3o especificado.
jsexception.no.input.parameter.specified=Nenhum par\u00E2metro de entrada especificado.
jsexception.no.olap.client.connection=Nenhuma conex\u00E3o de cliente OLAP encontrada.
jsexception.no.secure.olap.client.connection=Nenhuma conex\u00E3o de cliente OLAP segura encontrada.
jsexception.no.olap.model.created.for=Nenhum modelo OLAP criado para {0}.
jsexception.no.olap.model.name=Nenhum modelo OLAP especificado.
jsexception.no.olap.model.retrieved=Nenhum modelo OLAP pode ser recuperado.
jsexception.no.output.parameter.specified=Nenhum par\u00E2metro de sa\u00EDda especificado.
jsexception.no.persistent.class.mapped.to=Nenhuma classe persistente est\u00E1 mapeada para {0}.
jsexception.no.resource.data.provider.found=Nenhum provedor de dados de recurso encontrado para ID {0}.
jsexception.no.such.object.permission=A permiss\u00E3o do objeto especificado n\u00E3o existe.
jsexception.no.such.role=N\u00E3o existe fun\u00E7\u00E3o {0}.
jsexception.no.such.user=N\u00E3o existe usu\u00E1rio {0}.
jsexception.no.uri.or.recipient.given=Nenhum URI ou recipiente especificado.
jsexception.no.values.to.enumerate={0} n\u00E3o \u00E9 um URI de recurso v\u00E1lido.
jsexception.no.values.to.enumerate={0} n\\u00e3o \\u00e9 um URI de recurso v\\u00e1lido.
jsexception.null.uri=URI nulo.

jsexception.output.stream.already.closed=O fluxo de sa\u00EDda j\u00E1 est\u00E1 fechado.

jsexception.property.not.a.list=Propriedade {0} do bean {1} n\u00E3o \u00E9 uma propriedade de lista.
jsexception.property.not.a.map=Propriedade {0} do bean {1} n\u00E3o \u00E9 uma propriedade de mapa.
jsexception.property.not.a.text=Propriedade {0} do bean {1} n\u00E3o \u00E9 uma propriedade de texto.

jsexception.query.datasource.has.an.invalid.type=A fonte de dados de consulta tem um tipo inv\u00E1lido ({0}).

jsexception.report.job.not.found=Um trabalho de relat\u00F3rio com ID {0} n\u00E3o pode ser encontrado.
jsexception.report.resource.already.exists.no.overwrite=Recurso de sa\u00EDda {0} j\u00E1 existe e a bandeira de substitui\u00E7\u00E3o do trabalho n\u00E3o est\u00E1 definida.
jsexception.report.no.content.resource=Recurso {0} n\u00E3o \u00E9 um recurso de conte\u00FAdo.
jsexception.report.unit.datasource.has.an.invalid.type=A fonte de dados de unidade de relat\u00F3rio tem um tipo inv\u00E1lido ({0}).
jsexception.report.unknown.output.format=Formato de sa\u00EDda do relat\u00F3rio {0} n\u00E3o \u00E9 um formato conhecido.
jsexception.repository.uri.neither.report.nor.folder=O URI do reposit\u00F3rio {0} n\u00E3o \u00E9 uma unidade de relat\u00F3rio nem uma pasta.
jsexception.resource.already.exists=Recurso {0} j\u00E1 existe. Escolha um nome diferente.
jsexception.resource.copyTo.not.implemented=copyTo do recurso n\u00E3o est\u00E1 implementado.
jsexception.resource.copyFrom.not.implemented=copyFrom do recurso n\u00E3o est\u00E1 implementado.
jsexception.resource.does.not.exist=Recurso {0} n\u00E3o existe.
jsexception.resource.no.match.versions={0}: cliente vers\u00E3o {1} n\u00E3o corresponde \u00E0 vers\u00E3o do reposit\u00F3rio ({2}).
jsexception.resource.of.type.not.found=Recurso {0} do tipo {1} n\u00E3o pode ser encontrado.
jsexception.resource.not.report.unit=Recurso {0} n\u00E3o \u00E9 uma unidade de relat\u00F3rio.
jsexception.resourcelookup.not.a.resource=ResourceLookup n\u00E3o \u00E9 um recurso: {0}.
jsexception.folder.delete.root=A pasta raiz n\u00E3o pode ser exclu\u00EDda.
jsexception.report.template.not.found=O URI do reposit\u00F3rio {0} n\u00E3o \u00E9 um modelo de relat\u00F3rio.
jsexception.report.template.uri.not.specified=URI de modelo n\u00E3o foi especificado.

jsexception.selected.report.not.adhoc=O relat\u00F3rio selecionado n\u00E3o \u00E9 um relat\u00F3rio Ad Hoc. Unidades de relat\u00F3rios regulares n\u00E3o s\u00E3o suportadas.
jsexception.session.timeout.occurred=A sess\u00E3o de OLAP expirou.

jsexception.too.many.data.rows=O exportador do Excel falhou devido ao excesso de linhas de dados. Voc\u00EA pode alterar as configura\u00E7\u00F5es do exportador para uma p\u00E1gina por folha.

jsexception.unable.to.complete.request=O sistema n\u00E3o conseguiu concluir sua solicita\u00E7\u00E3o. Sua conversa terminou, expirou, ou foi invalidada.
jsexception.undefined.file.type=O tipo de arquivo n\u00E3o \u00E9 reconhecido.
jsexception.unknown.connection.type=O tipo de conex\u00E3o n\u00E3o foi reconhecido.
jsexception.unknown.parameter.type.for.multiple.value.input=O tipo de par\u00E2metro {0} n\u00E3o \u00E9 v\u00E1lido para a entrada de v\u00E1rios valores.
jsexception.unknown.permission.recipient.type=Tipo de recipiente de permiss\u00E3o {0} n\u00E3o \u00E9 reconhecido.
jsexception.unknown.property.filter.operation=Opera\u00E7\u00E3o do filtro de propriedade {0} n\u00E3o \u00E9 reconhecida.
jsexception.unknown.timezone=Fuso hor\u00E1rio {0} n\u00E3o \u00E9 reconhecido. 
jsexception.uri.not.found=URI {0} n\u00E3o pode ser encontrado no reposit\u00F3rio.
jsexception.user.credentials.are.expired=Credenciais do usu\u00E1rio {0} expiraram.
jsexception.user.disabled=Usu\u00E1rio {0} est\u00E1 desativado.
jsexception.user.expired=Usu\u00E1rio {0} expirou.
jsexception.user.locked=Usu\u00E1rio {0} est\u00E1 bloqueado.
jsexception.user.not.found=Usu\u00E1rio {0} n\u00E3o pode ser encontrado.

jsexception.move.folder.source.uri.ancestor.destination={0} n\u00E3o pode ser movido para {1}. O destino \u00E9 um filho da fonte.
jsexception.move.folder.to.same.folder=N\u00E3o \u00E9 poss\u00EDvel mover pasta {0} para a mesma pasta {1}.
jsexception.move.resource.to.same.folder=N\u00E3o \u00E9 poss\u00EDvel mover recurso {0} para a mesma pasta {1}.
jsexception.move.folder.path.already.exists=N\u00E3o \u00E9 poss\u00EDvel mover pasta {0} para {1}. A pasta de destino j\u00E1 cont\u00E9m um objeto com o mesmo nome.
jsexception.move.resource.path.already.exists=N\u00E3o \u00E9 poss\u00EDvel mover recurso {0} para {1}. O destino j\u00E1 cont\u00E9m um objeto com o mesmo nome.
jsexception.copy.resource.referenced.not.readable=Recurso {0} \u00E9 referenciado por outro recurso, mas n\u00E3o \u00E9 leg\u00EDvel.
jsexception.copy.resource.circular.reference=Foi detectada um refer\u00EAncia circular para recurso {0}.
jsexception.folder.moved=Pasta {0} foi movida para {1}.

report.scheduling.error.filling.report=O relat\u00F3rio n\u00E3o foi conclu\u00EDdo. Ocorreu um erro ao execut\u00E1-lo.
report.scheduling.error.exporting.report=Exporta\u00E7\u00E3o para {0} n\u00E3o foi conclu\u00EDda. Um erro interrompeu o processo.
report.scheduling.error.saving.to.repository={0} n\u00E3o foi salvo em um reposit\u00F3rio. Um erro interrompeu o processo.
report.scheduling.error.sending.email.notification=A notifica\u00E7\u00E3o de erro de trabalho n\u00E3o foi conclu\u00EDda. Ocorreu um erro durante o envio.
report.scheduling.error.system=O trabalho n\u00E3o foi conclu\u00EDdo. Ocorreu um erro do sistema ao execut\u00E1-lo.

exception.report.unrecognized.number.type=Tipo num\u00E9rico desconhecido {0}
exception.report.unrecognized.date.type=Tipo de data/hora desconhecido {0}
exception.report.unsupported.date.input.value=N\u00E3o \u00E9 poss\u00EDvel converter o valor de entrada {0} do tipo {1} para um par\u00E2metro de data/hora.
exception.report.unsupported.date.parameter.type=Tipo de data/hora n\u00E3o suportado {0}
exception.report.unsupported.input.control.data.type=Tipo de dados da entrada de controle {0} n\u00E3o \u00E9 suportado.

jsexception.view.report.could.not.load=A unidade do relat\u00F3rio n\u00E3o pode ser encontrada ou n\u00E3o pode ser carregada.
jsexception.view.page.does.not.exist=P\u00E1gina {0} n\u00E3o encontrada no relat\u00F3rio
jsexception.view.report.error=Ocorreu um erro durante a gera\u00E7\u00E3o do relat\u00F3rio
jsexception.export.unknown.argument=Op\u00E7\u00E3o {0} n\u00E3o \u00E9 reconhecida.

jsexception.mondrian.no.connection.for.resource=N\u00E3o existe conex\u00E3o Mondrian para recurso {0}.

jsexception.target.org.not.found=Organiza\u00E7\u00E3o alvo {0} n\u00E3o pode ser encontrada no reposit\u00F3rio.
jsexception.template.folder.not.found=N\u00E3o foi poss\u00EDvel localizar a pasta de modelos no reposit\u00F3rio.

jsexception.search.duplicate.label=J\u00E1 existe um objeto com o t\u00EDtulo {0} na pasta {1}.
jsexception.search.duplicate.name=J\u00E1 existe um objeto com o nome {0} na pasta {1}.

report.scheduling.error.saving.data.snapshot.disabled=Grava\u00E7\u00E3o de instant\u00E2neo de dados desativada.
report.scheduling.error.data.snapshot.not.populated=Instant\u00E2neo de dados n\u00E3o foi preenchido.
report.scheduling.error.data.snapshot.not.persistable=Instant\u00E2neo de dados n\u00E3o pode ser salvo.
report.scheduling.error.saving.data.snapshot.failed=Erro ao salvar instant\u00E2neo de dados.

exception.remote.resource.already.exists=Recurso {0} j\u00E1 existe.
exception.remote.resource.not.found=Recurso {0} n\u00E3o encontrado.
exception.remote.resource.type.not.supported=Tipo de recurso {0} n\u00E3o \u00E9 suportado por esta opera\u00E7\u00E3o.
exception.remote.folder.not.found=Pasta {0} n\u00E3o foi encontrada ou n\u00E3o \u00E9 uma pasta.
exception.remote.unexpected.error=Erro inesperado.
exception.remote.weak.password=Senha fraca.
exception.remote.attribute.permission.order.invalid=A permiss\u00E3o de atributo para {0} n\u00E3o pode ser modificada para uma permiss\u00E3o mais r\u00EDgida {1}. Escolha uma permiss\u00E3o que seja mais restritiva ou igual \u00E0 permiss\u00E3o herdada {2}.
exception.remote.attribute.permission.recipient.invalid=O destinat\u00E1rio da permiss\u00E3o de atributo {0} para {1} \u00E9 inv\u00E1lido.
exception.remote.resource.not.ready=Tarefa {0} ainda n\u00E3o terminada.
exception.remote.no.such.export.process=Nenhuma tarefa de exporta\u00E7\u00E3o com id {0}.
exception.remote.no.such.import.process=Nenhuma tarefa de importa\u00E7\u00E3o com id {0}.
exception.remote.access.denied=Acesso negado.
exception.remote.modification.not.allowed=Modifica\u00E7\u00E3o do recurso {0} n\u00E3o \u00E9 permitida.
exception.remote.illegal.parameter.value.error=Valor do par\u00E2metro \"{1}\" do par\u00E2metro \"{0}\" \u00E9 inv\u00E1lido.

exception.remote.query.reference.integrity.error=A consulta falhou ou faz refer\u00EAncias inapropriadas aos campos de consulta.
exception.remote.query.filter.reference.class.error=O filtro faz refer\u00EAncia ao campo {0} com um tipo {1} n\u00E3o suportado.
exception.remote.query.order.generic.reference.class.error=A instru\u00E7\u00E3o de ordem faz refer\u00EAncia ao campo {0} do tipo {1} n\u00E3o suportado.
exception.remote.query.order.header.null.reference.error=A instru\u00E7\u00E3o de ordem do cabe\u00E7alho n\u00E3o tem refer\u00EAncia a n\u00EDvel de consulta.
exception.remote.query.order.header.reference.class.error=A instru\u00E7\u00E3o de ordem do cabe\u00E7alho faz refer\u00EAncia ao campo {0} do tipo {1} n\u00E3o suportado.
exception.remote.query.expansion.header.null.reference.error=A instru\u00E7\u00E3o de expans\u00E3o do cabe\u00E7alho n\u00E3o tem refer\u00EAncia a n\u00EDvel de consulta.
exception.remote.query.expansion.level.reference.class.error=A instru\u00E7\u00E3o de expans\u00E3o do cabe\u00E7alho faz refer\u00EAncia ao campo {0} do tipo {1} n\u00E3o suportado.
exception.remote.query.expansion.level.ambiguous.reference.error=A expans\u00E3o do cabe\u00E7alho faz refer\u00EAncia a um campo que n\u00E3o \u00E9 exclusivamente identific\u00E1vel {0}.
exception.remote.query.aggregated.field.reference.class.error=A instru\u00E7\u00E3o de expans\u00E3o do cabe\u00E7alho faz refer\u00EAncia ao campo {0} do tipo {1} n\u00E3o suportado.

exception.remote.mandatory.parameter.error=Par\u00E2metro obrigat\u00F3rio \"{0}\" est\u00E1 ausente.
exception.remote.mandatory.olap.parameter.select.aggregations.error=O par\u00E2metro obrigat\u00F3rio \"select.aggregations\" est\u00E1 ausente.
exception.remote.mandatory.olap.parameter.groupBy.columns.error=O par\u00E2metro obrigat\u00F3rio \"groupBy.columns\" est\u00E1 ausente.
exception.remote.mandatory.olap.parameter.groupBy.aggregations.error=O par\u00E2metro obrigat\u00F3rio \"agrega\u00E7\u00F5es\" para \"groupBy.columns\" ou \"groupBy.rows\" est\u00E1 ausente.
exception.remote.parameter.groupBy.multiple.aggregations.error=Foram encontrados v\u00E1rios par\u00E2metros de \"agrega\u00E7\u00F5es\". Somente um par\u00E2metro \u00E9 permitido para \"groupBy.columns\" ou \"groupBy.rows\".
exception.remote.import.failed=Falha na importa\u00E7\u00E3o. Motivo: {0}
exception.remote.import.failed.zip.error=Falha na importa\u00E7\u00E3o. Motivo: n\u00E3o \u00E9 poss\u00EDvel ler o arquivo zip.
exception.remote.import.failed.content.error=Falha na importa\u00E7\u00E3o. Motivo: arquivo zip fornecido n\u00E3o \u00E9 arquivo de exporta\u00E7\u00E3o de Jasper Server v\u00E1lido.
exception.remote.resource.querying.not.supported=Recurso {0} n\u00E3o tem suporte para consultas
exception.remote.version.not.match=Falha na atualiza\u00E7\u00E3o: vers\u00F5es n\u00E3o correspondem
exception.remote.query.where.parameters.name.is.not.valid=O nome do par\u00E2metro \u00E9 inv\u00E1lido. O nome deve come\u00E7ar com o caractere alfab\u00E9tico e permitir apenas A-z_e n\u00FAmeros.
exception.remote.serialization.error= Erro de serializa\u00E7\u00E3o.

exception.remote.query.level.hierarchy.not.valid=Os n\u00EDveis de uma dimens\u00E3o t\u00EAm hierarquia diferente. Somente os n\u00EDveis de uma \u00FAnica hierarquia podem ser selecionados.
exception.remote.olap.query.limit.not.supported=O limite de consulta n\u00E3o \u00E9 suportado para OLAP.
exception.remote.query.calculated.field.expression.missing=Express\u00E3o de campo calculado ausente.
exception.remote.path.list.not.valid=O segmento do caminho cont\u00E9m caracteres inv\u00E1lidos
exception.remote.query.calculated.field.expression.not.valid=A express\u00E3o do campo calculado da consulta n\u00E3o \u00E9 v\u00E1lida.
exception.remote.timezone.is.not.valid=O fuso hor\u00E1rio {0} n\u00E3o \u00E9 v\u00E1lido.

#AWS data source specific exception messages
aws.exception.datasource.recovery.base=Ocorreu uma exce\u00E7\u00E3o durante a recupera\u00E7\u00E3o da fonte de dados AWS: {0}.
aws.exception.datasource.recovery.timeout=Pode haver um problema com a URL de JDBC, Configura\u00E7\u00F5es de Seguran\u00E7a de AWS ou o processo de recupera\u00E7\u00E3o de Fonte de dados AWS, que pode levar at\u00E9 2 minutos.
aws.exception.datasource.recovery.instance.not.active=A inst\u00E2ncia de fonte de dados AWS n\u00E3o est\u00E1 ativa.
aws.exception.datasource.recovery.is.not.possible=A fonte de dados AWS n\u00E3o pode ser recuperada automaticamente, pois seu JasperReports Server e a inst\u00E2ncia de banco de dados n\u00E3o est\u00E3o localizados no mesmo VPC.
aws.exception.datasource.recovery.public.ip.not.provided=Voc\u00EA deve fornecer o 'IP P\u00FAblico de Ingresso' deste servidor nas Configura\u00E7\u00F5es em Nuvem para usar a configura\u00E7\u00E3o e recupera\u00E7\u00E3o autom\u00E1tica da Fonte de dados AWS.
aws.exception.datasource.recovery.public.ip.not.determined=N\u00E3o foi poss\u00EDvel determinar o endere\u00E7o IP da inst\u00E2ncia para a recupera\u00E7\u00E3o de Fonte de Dados AWS.
aws.exception.datasource.load.default.credentials=Essa inst\u00E2ncia n\u00E3o pode usar <b>credenciais da inst\u00E2ncia EC2</b> para se conectar automaticamente a Amazon RDS e Amazon Redshift, porque n\u00E3o tem atribu\u00EDda uma Fun\u00E7\u00E3o de Gerenciamento de Acesso e Identidade (Identity and Access Management - IAM). Leia <a class='launcher inline' href='http://community.jaspersoft.com/jaspersoft-aws/launch' target='_blank'>Como Iniciar Jaspersoft para AWS</a> para aprender como iniciar um servidor que pode conectar automaticamente e com seguran\u00E7a a fontes de dados AWS.<br><br>Como alternativa voc\u00EA pode usar <b>credenciais AWS</b>.
aws.exception.datasource.rds.vpc.recovery=N\u00E3o \u00E9 poss\u00EDvel atribuir automaticamente o grupo de seguran\u00E7a VPC chamado {0} a inst\u00E2ncia de RDS {1}. A opera\u00E7\u00E3o n\u00E3o \u00E9 suportada por AWS API atualmente. Por favor atribuir manualmente o grupo de seguran\u00E7a para sua inst\u00E2ncia de RDS.
aws.exception.datasource.accessKey.invalid=Chave de acesso AWS \u00E9 inv\u00E1lida.
aws.exception.datasource.secretKey.invalid=Chave secreta AWS \u00E9 inv\u00E1lida.

#AZURE data source specific exception messages
azure.exception.datasource.recovery.public.ip.not.provided=Voc\u00EA deve fornecer o 'IP P\u00FAblico de Ingresso' deste servidor nas Configura\u00E7\u00F5es em Nuvem para usar a configura\u00E7\u00E3o e recupera\u00E7\u00E3o autom\u00E1tica de Fonte de dados do Azure.
azure.exception.datasource.recovery.firewall.rule.name.not.provided=Voc\u00EA deve fornecer o 'Nome da Regra de Firewall' deste servidor nas Configura\u00E7\u00F5es em Nuvem para usar a configura\u00E7\u00E3o e recupera\u00E7\u00E3o autom\u00E1tica da Fonte de dados do Azure.
azure.exception.datasource.recovery.server.name.not.provided=Voc\u00EA deve fornecer o 'Nome do Servidor' deste servidor para usar a configura\u00E7\u00E3o e recupera\u00E7\u00E3o autom\u00E1tica da Fonte de Dados do Azure.
azure.exception.datasource.recovery.subscription.id.not.provided=Voc\u00EA deve fornecer a 'ID de Assinatura' para usar a configura\u00E7\u00E3o e recupera\u00E7\u00E3o autom\u00E1tica do Banco de Dados do Azure.
azure.exception.datasource.recovery.key.store.file.not.provided=Voc\u00EA deve fornecer o 'Arquivo de Armazenamento Principal' para usar a configura\u00E7\u00E3o e recupera\u00E7\u00E3o autom\u00E1tica do Banco de Dados do Azure.
azure.exception.datasource.recovery.key.store.type.not.provided=Voc\u00EA deve fornecer o 'Tipo de Armazenamento Principal' para usar a configura\u00E7\u00E3o e recupera\u00E7\u00E3o do Banco de Dados do Azure automatizadas.
azure.exception.datasource.key.error=Erro ao ler o arquivo de certificado do reposit\u00F3rio. Verifique se o arquivo de certificado e a senha s\u00E3o v\u00E1lidos.
azure.exception.datasource.auth.error=Erro de autentica\u00E7\u00E3o. Verifique se a ID de assinatura e o certificado s\u00E3o v\u00E1lidos.
azure.exception.datasource.cannot.retrieve.database.list=N\u00E3o foi poss\u00EDvel recuperar os bancos de dados do gerenciamento de SQL.
azure.exception.datasource.cannot.ensure.firewall.rule=N\u00E3o foi poss\u00EDvel garantir a regra de firewall do Azure.
azure.exception.datasource.cannot.recover.datasource=N\u00E3o foi poss\u00EDvel recuperar o Banco de Dados do Azure

#Cluster specific exception messages
cluster.exception.session.attribute.missing=Um erro n\u00E3o relacionado ocorreu no servidor. Sua sess\u00E3o foi reiniciada, mas o trabalho n\u00E3o salvo foi perdido. Por favor, desculpe o transtorno.<p><p>Clique no link abaixo para voltar para a p\u00E1gina inicial e recome\u00E7ar: <a class=\"launcher inline\" href=\"home.html\">Ir \u00E0 p\u00E1gina inicial</a>. Se encontrar outro erro, entre em contato com o administrador.
cluster.exception.session.attribute.missing.popup=Um erro n\u00E3o relacionado ocorreu no servidor. Sua sess\u00E3o foi reiniciada, mas o trabalho n\u00E3o salvo foi perdido. Por favor, desculpe o transtorno.<p><p>Clique no bot\u00E3o abaixo para voltar para a p\u00E1gina inicial e recome\u00E7ar. Se encontrar outro erro, entre em contato com o administrador.

#Profile attributes substitution error and debug level messages
profile.attribute.exception.substitution.base = Ocorreu um erro de substitui\u00E7\u00E3o de atributo no campo \"{1}\" do recurso \"{0}\".
profile.attribute.substitution.not.found = O nome do atributo {0} n\u00E3o foi definido em {1}.
profile.attribute.substitution.not.found.in.resource = Ocorreu um erro de substitui\u00E7\u00E3o de atributo no campo \"{1}\" do recurso \"{0}\". O nome do atributo \"{2}\" n\u00E3o est\u00E1 definido em \"{3}\".
profile.attribute.substitution.category.invalid = No atributo \"{1}\", a categoria \"{0}\" n\u00E3o \u00E9 v\u00E1lida. Ela deve ser uma das \"{2}\".
profile.attribute.substitution.category.invalid.in.resource = Ocorreu um erro de substitui\u00E7\u00E3o de atributo no campo \"{1}\" do recurso \"{0}\". No atributo \"{3}\", a categoria \"{2}\" n\u00E3o \u00E9 v\u00E1lida. Ela deve ser uma das \"{4}\".
profile.attribute.debug.substitution.success = O atributo \"{0}\" foi substitu\u00EDdo no recurso \"{1}\". Novo valor de campo \"{2}\": \"{3}\".

#Query execution exceptions.
query.execution.not.found=A ID de execu\u00E7\u00E3o da consulta \"{0}\" n\u00E3o foi encontrada no servidor.
query.execution.cancelled=ID de execu\u00E7\u00E3o da consulta \"{0}\" foi cancelada.
query.datasource.invalid=A fonte de dados \"{0}\" causou um erro durante a execu\u00E7\u00E3o da consulta.
datasource.connection.failed=Falha na conex\u00E3o da fonte de dados.

#Paging exceptions.
paging.offset.out.of.range = O deslocamento de linha especificado \u00E9 inv\u00E1lido. O deslocamento deve estar entre \"{0}\" e \"{1}\".
paging.page.size.out.of.range = O tamanho da p\u00E1gina especificado \u00E9 inv\u00E1lido. O tamanho da p\u00E1gina deve superior a \"{0}\".
query.limit.out.of.range = O limite de consulta especificado \u00E9 inv\u00E1lido. O limite de consulta deve estar entre \"{0}\" e \"{1}\".
paging.axis.count.out.of.range=A contagem do eixo de pagina\u00E7\u00E3o n\u00E3o deve ser superior a 1 para v\u00E1rios n\u00EDveis ou 2 para consultas de v\u00E1rios eixos.

# Ad Hoc REST
query.where.parameter.not.valid=O par\u00E2metro \"{0}\" tem um valor inv\u00E1lido \"{1}\" para o operador \"{2}\".
query.field.ids.collision=As IDs do campo de consulta \"{0}\" entram em conflito com uma ID do campo de consulta ou um nome de campo da fonte de dados existente.
query.field.ids.metadata.field.collision=As IDs do campo de consulta \"{0}\" entram em conflito o nome de campo dos metadados existente.
query.parameter.name.query.field.id.collision=O nome do par\u00E2metro de consulta \"{0}\" est\u00E1 em conflito com uma ID do campo de consulta existente.
query.parameter.name.metadata.field.collision=O nome do par\u00E2metro de consulta \"{0}\" est\u00E1 em conflito com o campo de metadados.
report.missing.data.source.fields=O relat\u00F3rio cont\u00E9m um ou mais itens que n\u00E3o est\u00E3o nos dados de origem. Voc\u00EA deve editar a exibi\u00E7\u00E3o Ad Hoc usada para criar este relat\u00F3rio e salv\u00E1-lo novamente.
adhoc.missing.data.source.fields=A exibi\u00E7\u00E3o cont\u00E9m um ou mais itens que n\u00E3o est\u00E3o nos dados de origem. Voc\u00EA deve editar a exibi\u00E7\u00E3o Ad Hoc.
query.in.memory.datasource.type.not.supported=O valor para \"{0}\" n\u00E3o \u00E9 v\u00E1lido. A fonte de dados na mem\u00F3ria \u00E9 do tipo \"{1}\", que n\u00E3o \u00E9 suportado para execu\u00E7\u00E3o de consulta.
expression.representation.required = Em \"{0}\", o objeto da express\u00E3o ou uma sequ\u00EAncia de caracteres da express\u00E3o deve ser especificada, mas ambas as representa\u00E7\u00F5es s\u00E3o nulas.
query.datasource.not.found=O URI da fonte de dados \"{0}\" n\u00E3o foi encontrado no servidor.
query.datasource.access.denied=Voc\u00EA n\u00E3o tem permiss\u00E3o para acessar a fonte de dados \"{0}\".
query.aggregate.definition.error=A defini\u00E7\u00E3o agregada n\u00E3o pode ter uma fun\u00E7\u00E3o agregada e uma express\u00E3o.
query.fields.from.multiple.dataislands=Os campos de consulta \"{0}\" e \"{1}\" est\u00E3o em ilhas de dados separadas e n\u00E3o podem ser consultados juntos.
query.datasource.type.not.supported=A fonte de dados \"{0}\" \u00E9 um tipo que n\u00E3o \u00E9 suportado para execu\u00E7\u00E3o de consulta.
query.datasource.olap.view.not.supported=A fonte de dados \"{0}\" \u00E9 baseada em uma exibi\u00E7\u00E3o OLAP, que n\u00E3o \u00E9 suportada para execu\u00E7\u00E3o de consulta.
query.where.expression.type.not.supported=A express\u00E3o de consulta WHERE do tipo \"{0}\" n\u00E3o \u00E9 suportada.
query.expression.not.valid=A express\u00E3o da consulta n\u00E3o \u00E9 v\u00E1lida.
query.aggregate.expression.not.valid=A express\u00E3o de agrega\u00E7\u00E3o \"{1}\" no campo agregado \"{0}\" n\u00E3o \u00E9 v\u00E1lida.
query.aggregation.expression.not.valid=A express\u00E3o de agrega\u00E7\u00E3o da consulta n\u00E3o \u00E9 v\u00E1lida

query.select.illegal.fields.state=Sele\u00E7\u00E3o simult\u00E2nea de campos e campos distintos n\u00E3o s\u00E3o permitidos

query.aggregation.function.name.not.valid=O nome da fun\u00E7\u00E3o de agrega\u00E7\u00E3o \"{1}\" no campo agregado \"{0}\" n\u00E3o \u00E9 uma fun\u00E7\u00E3o reconhecida.
query.groupBy.allGroup.not.first=Nos grupos de consulta \"{0}\", \"allGroup\" deve estar na primeira posi\u00E7\u00E3o.
query.groupBy.categorizer.not.valid=O categorizador GROUP BY \"{0}\" n\u00E3o tem um nome v\u00E1lido.
query.multiAxis.aggregation.is.empty=A matriz de agrega\u00E7\u00E3o de uma consulta de v\u00E1rios eixos n\u00E3o pode estar em branco.
query.orderBy.topOrBottom.limit.not.valid=O limite de ORDER BY \"{0}\" tem um valor de \"{1}\", mas n\u00E3o pode ser inferior a 1.
query.orderBy.level.reference.not.valid=O n\u00EDvel ORDER BY da consulta \"{0}\" n\u00E3o pode ser resolvido. O sinalizador de agrega\u00E7\u00E3o est\u00E1 ausente ou o fieldRef n\u00E3o \u00E9 v\u00E1lido.

query.where.parameters.expression.not.valid=As express\u00F5es de par\u00E2metro na cl\u00E1usula WHERE n\u00E3o s\u00E3o suportadas ou n\u00E3o s\u00E3o v\u00E1lidas.
query.where.parameters.expression.type.not.valid=O par\u00E2metro \"{0}\" da express\u00E3o WHERE \u00E9 inv\u00E1lido para o operador \"{1}\". Ele deve ser um dos seguintes tipos: \"{2}\"
query.details.unsupported=As consultas de v\u00E1rios eixos n\u00E3o suportam detalhes. A express\u00E3o SELECT n\u00E3o pode definir nenhum campo.
query.invalid.structure=A consulta deve conter pelo menos uma cl\u00E1usula n\u00E3o vazia, a express\u00E3o SELECT ou GROUP BY.
query.transformation.topn.not.allowed.aggregations.in.rows=Os filtros Principais N ou N inferiores n\u00E3o s\u00E3o permitidos quando uma consulta de v\u00E1rios eixos contiver agrega\u00E7\u00F5es em linhas.
attribute.patterns.contains.invalid = A lista de padr\u00F5es de atributos cont\u00E9m um padr\u00E3o inv\u00E1lido {0}. Ela n\u00E3o cont\u00E9m os pr\u00F3ximos grupos de captura de nomes: {1}

query.expression.operands.size.out.of.bound=O tamanho dos operadores de express\u00F5es da consulta \"{0}\" deve ter entre \"{1}\" e \"{2}\".
query.expansion.level.reference.not.valid = O n\u00EDvel de expans\u00E3o da consulta \"{0}\" n\u00E3o pode ser resolvido.
query.metadata.fields.not.found = Os campos de consulta \"{0}\" n\u00E3o existem na fonte de dados.