#
# Copyright (C) 2005 - 2019 TIBCO Software Inc. All rights reserved.
# http://www.jaspersoft.com.
#
# Unless you have purchased a commercial license agreement from Jaspersoft,
# the following license terms apply:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

jsexception.access.denied=Vous n\u2019\u00EAtes pas autoris\u00E9 \u00E0 effectuer l\u2019action demand\u00E9e. Connectez-vous avec un compte d\u2019utilisateur autoris\u00E9, si cela est possible.
jsexception.any={0}

jsexception.bean.has.no.method=Le Bean {0} ne comporte pas de m\u00E9thode {1}.
jsexception.bean.name.not.found.for.interface=Aucun nom de Bean trouv\u00E9 pour l\u2019interface {0}.
jsexception.bean.no.name=Impossible de trouver un Bean portant le nom {0}.
jsexception.bean.not.a.ReportDataSourceService=Le Bean {0} n\u2019est pas un ReportDataSourceService.

jsexception.call.not.supported=L\u2019appel n\u2019est pas pris en charge par les objets de consultation de ressources.
jsexception.connection.type.not.suported=Le type de connexion n\u2019est pas pris en charge.
jsexception.connection.uri.not.specified=L\u2019URI de connexion n\u2019est pas sp\u00E9cifi\u00E9e.
jsexception.could.not.find.resource.with.uri=Impossible de trouver la ressource associ\u00E9e \u00E0 l\u2019URI {0}. 
jsexception.could.not.find.content.resource.with.uri=Impossible de trouver la ressource de contenu associ\u00E9e \u00E0 l\u2019URI {0}.
jsexception.unexpected.resource.type.at.uri=Type inattendu ({0}) de la ressource avec l''URI {1} 

jsexception.default.message=Une erreur inexpliqu\u00E9e s\u2019est produite. Contactez votre administrateur syst\u00E8me.

jsexception.error.creating.connection=Une erreur s\u2019est produite pendant la cr\u00E9ation de la connexion. Veuillez r\u00E9essayer.
jsexception.parameter.has.multiple.values=Le param\u00E8tre {0} poss\u00E8de plusieurs valeurs.

jsexception.parameter.has.no.value=Le param\u00E8tre {0} ne comporte aucune valeur.


jsexception.failed.to.create.connection=Impossible d\u2019\u00E9tablir la connexion.
jsexception.failed.to.save.connection=La connexion n\u2019a pas \u00E9t\u00E9 enregistr\u00E9e.
jsexception.failed.to.save.connection.changes=Les modifications apport\u00E9es \u00E0 la connexion n\u2019ont pas \u00E9t\u00E9 enregistr\u00E9es.
jsexception.file.resource.is.reference=La ressource de fichier {0} est une r\u00E9f\u00E9rence et ne contient aucune donn\u00E9e.
jsexception.file.resource.no.match.type=Le type d\u00E9clar\u00E9 de la ressource ({0}) ne correspond pas au type de r\u00E9f\u00E9rence r\u00E9el ({1}).
jsexception.folder.already.exists=Un dossier portant le nom {0} existe d\u00E9j\u00E0. Entrer un autre nom.
jsexception.folder.details.not.found=Les d\u00E9tails du dossier {0} sont introuvables dans les informations d\u2019importation. 
jsexception.folder.not.found=Impossible de trouver le dossier {0}. 
jsexception.folder.not.found.at=Le dossier n\u2019est pas \u00E0 {0}.
jsexception.folder.duplicate.name=Un dossier portant le nom {0} existe d\u00E9j\u00E0 dans {1}.
jsexception.folder.duplicate.label=Le libell\u00E9 {0} est en double dans le dossier {1}.
jsexception.folder.too.long.uri=L''URI du dossier est trop long. La longueur maximale est de {0} caract\u00E8res.
jsexception.folder.creation.not.allowed={0} est un nom r\u00E9serv\u00E9 et non autoris\u00E9 dans {1}.

jsexception.got.null.schema.source.wrapper=Le subflow a renvoy\u00E9 une classe enveloppante de source de sch\u00E9ma nulle.
jsexception.got.null.access.grant.source.wrapper=Le subflow a renvoy\u00E9 une classe enveloppante de source d\u2019autorisation d\u2019acc\u00E8s nulle.
jsexception.got.null.connection.back=Le subflow a renvoy\u00E9 une connexion nulle.

jsexception.implementation.class.does.not.implement=La classe d\u2019impl\u00E9mentation {0} n\u2019int\u00E8gre pas {1}.
jsexception.implementation.class.not.found=Impossible de trouver la classe d\u2019impl\u00E9mentation pour {0}.
jsexception.import.directory.not.found=Impossible de trouver le r\u00E9pertoire d\u2019importation {0}.
jsexception.import.module.not.found=Impossible de trouver le module d\u2019importation {0}.
jsexception.import.multiple.values.for.single.parameter=Plusieurs valeurs ont \u00E9t\u00E9 d\u00E9tect\u00E9es pour le param\u00E8tre {0} du rapport {1}, qui ne peut en comporter qu\u2019une.
jsexception.input.stream.exhausted=Le flux d\u2019entr\u00E9e \u00E9tait satur\u00E9 avant la lecture de {0} octets.
jsexception.invalid.bean.datasource=La source de donn\u00E9es Bean {0} n\u2019est pas valide.
jsexception.invalid.class.attribute.for.model.tag=L\u2019attribut de classe de la balise mod\u00E8le, ressource {0}, n\u2019est pas valide.
jsexception.invalid.jdbc.datasource=La source de donn\u00E9es JDBC {0} n\u2019est pas valide.
jsexception.invalid.aws.datasource=La source de donn\u00E9es AWS {0} n\u2019est pas valide.
jsexception.invalid.azureSql.datasource=La source de donn\u00E9es Azure SQL {0} n\u2019est pas valide.
jsexception.invalid.jndi.jdbc.datasource=La source de donn\u00E9es JNDI JDBC {0} n\u2019est pas valide.
jsexception.invalid.olap.datasource=La source de donn\u00E9es OLAP {0} n\u2019est pas valide.
jsexception.invalid.resource.reference.source=La source de r\u00E9f\u00E9rence de la ressource {0} n\u2019est pas valide.
jsexception.invalid.session=La session actuelle n\u2019est pas valide. V\u00E9rifiez que le serveur fonctionne et connectez-vous \u00E0 nouveau.
jsexception.invalid.uri=L''URI {0} n''est pas valide.

jsexception.jar.entry.not.found=Impossible de trouver une entr\u00E9e JAR pour l\u2019URL {0}.
jsexception.jar.malformed.url=Syntaxe JAR incorrecte pour l\u2019URL {0}.
jsexception.jasperprint.not.found=Impossible de trouver l\u2019objet JasperPrint {0}.

jsexception.job.has.more.than.one.trigger=Le travail {0} poss\u00E8de plusieurs d\u00E9clencheurs.
jsexception.job.no.versions.match=La version client {0} n\u2019est pas la derni\u00E8re version ({1}).
jsexception.job.unknown.calendar.trigger.days.type=Type de jours du d\u00E9clencheur de calendrier inconnu {0}.
jsexception.job.unknown.interval.unit=Unit\u00E9 d\u2019intervalle de travail de rapport inconnue {0}.
jsexception.job.unknown.start.type=Type de d\u00E9marrage du travail de rapport inconnu {0}.
jsexception.job.unknown.trigger.bean.class=Classe Bean du d\u00E9clencheur de travail du rapport inconnue {0}.
jsexception.job.unknown.trigger.type=Type de d\u00E9clencheur du travail de rapport {0} inconnu.

jsexception.missing.olap.connection=Connexion\u00A0OLAP manquante.
jsexception.missing.olap.connection.reference=R\u00E9f\u00E9rence de connexion\u00A0OLAP manquante.
jsexception.mondrian.jdbc.datasource.has.an.invalid.type=Le type {0} de la source de donn\u00E9es JDBC de la connexion Mondrian n\u2019est pas valide.

jsexception.no.connection.selected=Aucune connexion n\u2019a \u00E9t\u00E9 s\u00E9lectionn\u00E9e.
jsexception.no.export.folder.specified=Aucun dossier d\u2019exportation n\u2019a \u00E9t\u00E9 sp\u00E9cifi\u00E9.
jsexception.no.export.zip.file.specified=Aucun fichier\u00A0ZIP d\u2019exportation n\u2019a \u00E9t\u00E9 sp\u00E9cifi\u00E9.
jsexception.no.import.folder.specified=Aucun dossier d\u2019importation n\u2019a \u00E9t\u00E9 indiqu\u00E9.
jsexception.no.import.zip.file.specified=Aucun fichier\u00A0ZIP d\u2019importation n\u2019a \u00E9t\u00E9 indiqu\u00E9.
jsexception.no.input.parameter.specified=Aucun param\u00E8tre d\u2019entr\u00E9e n\u2019a \u00E9t\u00E9 d\u00E9fini.
jsexception.no.olap.client.connection=Aucune connexion au client OLAP n\u2019a \u00E9t\u00E9 trouv\u00E9e.
jsexception.no.secure.olap.client.connection=Aucune connexion au client OLAP s\u00E9curis\u00E9e n\u2019a \u00E9t\u00E9 trouv\u00E9e.
jsexception.no.olap.model.created.for=Aucun mod\u00E8le OLAP n\u2019a \u00E9t\u00E9 cr\u00E9\u00E9 pour {0}.
jsexception.no.olap.model.name=Aucun mod\u00E8le OLAP n\u2019a \u00E9t\u00E9 sp\u00E9cifi\u00E9.
jsexception.no.olap.model.retrieved=Aucun mod\u00E8le\u00A0OLAP n\u2019a pu \u00EAtre r\u00E9cup\u00E9r\u00E9.
jsexception.no.output.parameter.specified=Aucun param\u00E8tre de sortie n\u2019a \u00E9t\u00E9 sp\u00E9cifi\u00E9.
jsexception.no.persistent.class.mapped.to=Aucune classe persistante ne correspond \u00E0 {0}.
jsexception.no.resource.data.provider.found=Aucun fournisseur de donn\u00E9es de ressource n\u2019a \u00E9t\u00E9 trouv\u00E9 pour ID {0}.
jsexception.no.such.object.permission=L\u2019autorisation d\u2019objet sp\u00E9cifi\u00E9e n\u2019existe pas.
jsexception.no.such.role=Il n\u2019existe aucun r\u00F4le {0}.
jsexception.no.such.user=Il n\u2019existe aucun utilisateur {0}.
jsexception.no.uri.or.recipient.given=Aucun destinataire ou URI n\u2019a \u00E9t\u00E9 sp\u00E9cifi\u00E9.
jsexception.no.values.to.enumerate={0} n\u2019est pas une URI de ressource valide.
jsexception.no.values.to.enumerate={0} n\\u2019est pas une URI de ressource valide.
jsexception.null.uri=URI nulle.

jsexception.output.stream.already.closed=Le flux de sortie est d\u00E9j\u00E0 ferm\u00E9.

jsexception.property.not.a.list=La propri\u00E9t\u00E9 {0} de Bean {1} n\u2019est pas une propri\u00E9t\u00E9 de la liste.
jsexception.property.not.a.map=La propri\u00E9t\u00E9 {0} de Bean {1} n\u2019est une propri\u00E9t\u00E9 de la carte.
jsexception.property.not.a.text=La propri\u00E9t\u00E9 {0} de Bean {1} n\u2019est pas une propri\u00E9t\u00E9 du texte.

jsexception.query.datasource.has.an.invalid.type=Le type de la source de donn\u00E9es de la requ\u00EAte n\u2019est pas valide ({0}).

jsexception.report.job.not.found=Aucun travail de rapport portant l\u2019ID {0} n\u2019a \u00E9t\u00E9 trouv\u00E9.
jsexception.report.resource.already.exists.no.overwrite=La ressource de sortie {0} existe d\u00E9j\u00E0 et la balise de remplacement de travail n\u2019est pas d\u00E9finie.
jsexception.report.no.content.resource=La ressource {0} n\u2019est pas une ressource de contenu.
jsexception.report.unit.datasource.has.an.invalid.type=Le type de la source de donn\u00E9es de l\u2019unit\u00E9 de rapport n\u2019est pas valide ({0}).
jsexception.report.unknown.output.format=Le format de sortie du rapport {0} est inconnu.
jsexception.repository.uri.neither.report.nor.folder=L\u2019URI du r\u00E9f\u00E9rentiel {0} ne correspond ni \u00E0 une unit\u00E9 de rapport, ni \u00E0 un dossier.
jsexception.resource.already.exists=La ressource {0} existe d\u00E9j\u00E0. Entrer un autre nom.
jsexception.resource.copyTo.not.implemented=La ressource copyTo n\u2019a pas \u00E9t\u00E9 impl\u00E9ment\u00E9e.
jsexception.resource.copyFrom.not.implemented=La ressource copyFrom n\u2019a pas \u00E9t\u00E9 impl\u00E9ment\u00E9e.
jsexception.resource.does.not.exist=La ressource {0} n\u2019existe pas.
jsexception.resource.no.match.versions={0} : la version client ({1}) ne correspond pas \u00E0 la version du r\u00E9f\u00E9rentiel ({2}).
jsexception.resource.of.type.not.found=La ressource {0} de type {1} est introuvable.
jsexception.resource.not.report.unit=La ressource {0} n\u2019est pas une unit\u00E9 de rapport.
jsexception.resourcelookup.not.a.resource=ResourceLookup n\u2019est pas une ressource\u00A0: {0}.
jsexception.folder.delete.root=Impossible de supprimer le dossier racine.
jsexception.report.template.not.found=L'URL du r\u00E9f\u00E9rentiel {0} n'est pas un mod\u00E8le de rapport.
jsexception.report.template.uri.not.specified=L\u2019URI de mod\u00E8le n\u2019est pas sp\u00E9cifi\u00E9e.

jsexception.selected.report.not.adhoc=Le rapport s\u00E9lectionn\u00E9 n\u2019est pas un rapport \u00E0 la demande. Les unit\u00E9s de rapport standard ne sont pas prises en charge.
jsexception.session.timeout.occurred=La session\u00A0OLAP a expir\u00E9.

jsexception.too.many.data.rows=\u00C9chec de l\u2019exportation Excel en raison d\u2019un trop grand nombre de lignes de donn\u00E9es. Modifier les param\u00E8tres d\u2019exportation pour afficher une seule page par feuille.

jsexception.unable.to.complete.request=Le syst\u00E8me n\u2019a pas pu terminer votre requ\u00EAte. Votre conversation s\u2019est peut-\u00EAtre termin\u00E9e, a expir\u00E9 ou a \u00E9t\u00E9 rejet\u00E9e.
jsexception.undefined.file.type=Le type de fichier n\u2019est pas reconnu.
jsexception.unknown.connection.type=Le type de connexion n\u2019est pas reconnu.
jsexception.unknown.parameter.type.for.multiple.value.input=Le type de param\u00E8tre {0} n\u2019est pas valide pour l\u2019entr\u00E9e de valeurs multiples.
jsexception.unknown.permission.recipient.type=Le type de destinataire d\u2019autorisation {0} est inconnu.
jsexception.unknown.property.filter.operation=L\u2019op\u00E9ration de filtre de propri\u00E9t\u00E9 {0} est inconnue.
jsexception.unknown.timezone=Le fuseau horaire {0} est inconnu. 
jsexception.uri.not.found=L\u2019URI {0} est introuvable dans le r\u00E9f\u00E9rentiel.
jsexception.user.credentials.are.expired=Les donn\u00E9es d\u2019identification de l\u2019utilisateur {0} sont arriv\u00E9es \u00E0 expiration.
jsexception.user.disabled=La session de l\u2019utilisateur {0} est d\u00E9sactiv\u00E9e.
jsexception.user.expired=La session de l\u2019utilisateur {0} a expir\u00E9.
jsexception.user.locked=La session de l\u2019utilisateur {0} est verrouill\u00E9e.
jsexception.user.not.found=Impossible de trouver l\u2019utilisateur {0}.

jsexception.move.folder.source.uri.ancestor.destination={0} ne peut pas \u00EAtre d\u00E9plac\u00E9 vers {1}. Le dossier de destination est un dossier enfant du dossier source.
jsexception.move.folder.to.same.folder=Vous ne pouvez pas d\u00E9placer le dossier {0} dans le m\u00EAme dossier {1}.
jsexception.move.resource.to.same.folder=Vous ne pouvez pas d\u00E9placer la ressource {0} dans le m\u00EAme dossier {1}.
jsexception.move.folder.path.already.exists=Vous ne pouvez pas d\u00E9placer le dossier {0} vers {1}. Le dossier de destination contient d\u00E9j\u00E0 un objet portant le m\u00EAme nom.
jsexception.move.resource.path.already.exists=Vous ne pouvez pas d\u00E9placer la ressource {0} vers {1}. Le dossier de destination contient d\u00E9j\u00E0 un objet portant le m\u00EAme nom.
jsexception.copy.resource.referenced.not.readable=Bien que la ressource {0} soit r\u00E9f\u00E9renc\u00E9e par une autre ressource, elle n\u2019est pas lisible.
jsexception.copy.resource.circular.reference=Une r\u00E9f\u00E9rence circulaire a \u00E9t\u00E9 d\u00E9tect\u00E9e pour la ressource {0}.
jsexception.folder.moved=Le dossier {0} a \u00E9t\u00E9 d\u00E9plac\u00E9 dans {1}.

report.scheduling.error.filling.report=Le rapport n\u2019a pas \u00E9t\u00E9 termin\u00E9. Une erreur s\u2019est produite pendant son ex\u00E9cution.
report.scheduling.error.exporting.report=L\u2019exportation vers {0} n\u2019a pas \u00E9t\u00E9 termin\u00E9e. Une erreur a interrompu le processus.
report.scheduling.error.saving.to.repository={0} n\u2019a pas \u00E9t\u00E9 enregistr\u00E9 dans le r\u00E9f\u00E9rentiel. Une erreur a interrompu le processus.
report.scheduling.error.sending.email.notification=La notification de t\u00E2che erron\u00E9e n\u2019a pas \u00E9t\u00E9 termin\u00E9e. Une erreur s\u2019est produite pendant son envoi.
report.scheduling.error.system=Le travail n\u2019a pas \u00E9t\u00E9 termin\u00E9. Une erreur syst\u00E8me s\u2019est produite pendant son ex\u00E9cution.

exception.report.unrecognized.number.type=Type num\u00E9rique {0} non reconnu.
exception.report.unrecognized.date.type=Type date/heure {0} non reconnu.
exception.report.unsupported.date.input.value=Vous ne pouvez pas convertir la valeur d\u2019entr\u00E9e {0} de type {1} en param\u00E8tre date/heure.
exception.report.unsupported.date.parameter.type=Type date/heure {0} non pris en charge.
exception.report.unsupported.input.control.data.type=Le type de donn\u00E9es de contr\u00F4le d''entr\u00E9e {0} n''est pas pris en charge.

jsexception.view.report.could.not.load=Impossible de trouver ou de charger l\u2019unit\u00E9 de rapport.
jsexception.view.page.does.not.exist=Page {0} introuvable dans le rapport.
jsexception.view.report.error=Une erreur s'est produite lors de la g\u00E9n\u00E9ration du rapport.
jsexception.export.unknown.argument=L\u2019option {0} est inconnue.

jsexception.mondrian.no.connection.for.resource=Il n\u2019existe aucune connexion Mondrian pour la ressource {0}.

jsexception.target.org.not.found=L\u2019organisation cible {0} est introuvable dans le r\u00E9f\u00E9rentiel.
jsexception.template.folder.not.found=Le dossier de mod\u00E8le est introuvable dans le r\u00E9f\u00E9rentiel.

jsexception.search.duplicate.label=Un objet portant le libell\u00E9 {0} existe d\u00E9j\u00E0 dans le dossier {1}.
jsexception.search.duplicate.name=Un objet portant le nom {0} existe d\u00E9j\u00E0 dans le dossier {1}.

report.scheduling.error.saving.data.snapshot.disabled=L'enregistrement des instantan\u00E9s de donn\u00E9es est d\u00E9sactiv\u00E9.
report.scheduling.error.data.snapshot.not.populated=Impossible de remplir l'instantan\u00E9 de donn\u00E9es.
report.scheduling.error.data.snapshot.not.persistable=Impossible d'enregistrer l'instantan\u00E9 de donn\u00E9es.
report.scheduling.error.saving.data.snapshot.failed=Erreur lors de l'enregistrement de l'instantan\u00E9 de donn\u00E9es.

exception.remote.resource.already.exists=La ressource {0} existe d\u00E9j\u00E0.
exception.remote.resource.not.found=Ressource {0} introuvable.
exception.remote.resource.type.not.supported=La ressource de type {0} n\u2019est pas prise en charge par cette op\u00E9ration.
exception.remote.folder.not.found=Dossier {0} introuvable ou n\u2019est pas un dossier.
exception.remote.unexpected.error=Erreur inattendue.
exception.remote.weak.password=Mot de passe faible.
exception.remote.attribute.permission.order.invalid=L\u2019autorisation d\u2019attribut pour {0} ne peut pas \u00EAtre modifi\u00E9e en une autorisation plus forte {1}. Choisissez une autorisation plus restrictive ou \u00E9gale \u00E0 l\u2019autorisation h\u00E9rit\u00E9e {2}.
exception.remote.attribute.permission.recipient.invalid=Le destinataire d\u2019autorisation d\u2019attribut {0} pour {1} n\u2019est pas valide.
exception.remote.resource.not.ready=La t\u00E2che {0} n''est pas encore termin\u00E9e.
exception.remote.no.such.export.process=Aucune t\u00E2che d''exportation ne poss\u00E8de l''identifiant {0}.
exception.remote.no.such.import.process=Aucune t\u00E2che d''importation ne poss\u00E8de l''identifiant {0}.
exception.remote.access.denied=Acc\u00E8s refus\u00E9.
exception.remote.modification.not.allowed=Une modification de la ressource {0} n\u2019est pas autoris\u00E9e.
exception.remote.illegal.parameter.value.error=La valeur \"{1}\" du param\u00E8tre \"{0}\" n\u2019est pas valide.

exception.remote.query.reference.integrity.error=La requ\u00EAte comporte des r\u00E9f\u00E9rences inappropri\u00E9es ou rompues aux champs de la requ\u00EAte.
exception.remote.query.filter.reference.class.error=Type du champ de r\u00E9f\u00E9rences au filtre {0} non pris en charge ({1})
exception.remote.query.order.generic.reference.class.error=Type du champ de r\u00E9f\u00E9rences \u00E0 l\u2019\u00E9nonc\u00E9 d\u2019ordre {0} non pris en charge ({1})
exception.remote.query.order.header.null.reference.error=L\u2019\u00E9nonc\u00E9 d\u2019ordre dans l\u2019en-t\u00EAte ne comporte aucune r\u00E9f\u00E9rence au niveau de requ\u00EAte
exception.remote.query.order.header.reference.class.error=Type du champ de r\u00E9f\u00E9rences \u00E0 l\u2019\u00E9nonc\u00E9 d\u2019ordre dans l\u2019en-t\u00EAte {0} non pris en charge ({1})
exception.remote.query.expansion.header.null.reference.error=L\u2019\u00E9nonc\u00E9 de croissance dans l\u2019en-t\u00EAte ne comporte aucune r\u00E9f\u00E9rence au niveau de requ\u00EAte
exception.remote.query.expansion.level.reference.class.error=Type du champ de r\u00E9f\u00E9rences \u00E0 l\u2019\u00E9nonc\u00E9 de croissance dans l\u2019en-t\u00EAte {0} non pris en charge ({1})
exception.remote.query.expansion.level.ambiguous.reference.error=Le champ de r\u00E9f\u00E9rence \u00E0 l\u2019\u00E9nonc\u00E9 de croissance dans l\u2019en-t\u00EAte {0} n\u2019est pas identifiable de mani\u00E8re unique
exception.remote.query.aggregated.field.reference.class.error=Type du champ de r\u00E9f\u00E9rences \u00E0 l\u2019\u00E9nonc\u00E9 de croissance dans l\u2019en-t\u00EAte {0} non pris en charge ({1})

exception.remote.mandatory.parameter.error=Le param\u00E8tre obligatoire ''{0}'' est manquant.
exception.remote.mandatory.olap.parameter.select.aggregations.error=Le param\u00E8tre obligatoire \"select.aggregations\" est manquant.
exception.remote.mandatory.olap.parameter.groupBy.columns.error=Le param\u00E8tre obligatoire \"groupBy.columns\" est manquant.
exception.remote.mandatory.olap.parameter.groupBy.aggregations.error=Il manque le param\u00E8tre obligatoire \"agr\u00E9gations\" pour \"groupBy.columns\" ou \"groupBy.rows\".
exception.remote.parameter.groupBy.multiple.aggregations.error=De multiples param\u00E8tres \"agr\u00E9gations\" ont \u00E9t\u00E9 trouv\u00E9s. Un seul param\u00E8tre est autoris\u00E9 pour \"groupBy.columns\" ou \"groupBy.rows\"
exception.remote.import.failed=\u00C9chec de l''importation. Cause : {0}
exception.remote.import.failed.zip.error=\u00C9chec de l'importation. Cause : Impossible de lire le fichier compress\u00E9.
exception.remote.import.failed.content.error=\u00C9chec de l\u2019importation. Cause : le fichier zip fourni n\u2019est pas un fichier d\u2019exportation JasperReports Server valide.
exception.remote.resource.querying.not.supported=La ressource {0} ne prend pas en charge l\u2019interrogation.
exception.remote.version.not.match=Echec de la mise \u00E0 jour : les versions ne correspondent pas.
exception.remote.query.where.parameters.name.is.not.valid=Le nom de param\u00E8tre est invalide. Le nom doit commencer par une lettre de l'alphabet et contenir uniquement les caract\u00E8res A-z_et des chiffres
exception.remote.serialization.error= Erreur de s\u00E9rialisation.

exception.remote.query.level.hierarchy.not.valid=Des niveaux dans une dimension ont une hi\u00E9rarchie diff\u00E9rente. Seuls les niveaux dans une hi\u00E9rarchie unique peuvent \u00EAtre s\u00E9lectionn\u00E9s.
exception.remote.olap.query.limit.not.supported=Le nombre limite de requ\u00EAtes n'est pas pris en charge pour OLAP.
exception.remote.query.calculated.field.expression.missing=Expression du champ calcul\u00E9 absente.
exception.remote.path.list.not.valid=Le segment du chemin contient des caract\u00E8res invalides.
exception.remote.query.calculated.field.expression.not.valid=L'expression du champ calcul\u00E9 de la requ\u00EAte n'est pas valide.
exception.remote.timezone.is.not.valid=Le fuseau horaire {0} n''est pas valide.

#AWS data source specific exception messages
aws.exception.datasource.recovery.base=Une exception s\u2019est produite lors de la r\u00E9cup\u00E9ration de la source de donn\u00E9es AWS : {0}.
aws.exception.datasource.recovery.timeout=Il peut s\u2019agir d\u2019un probl\u00E8me li\u00E9 \u00E0 l\u2019URL JDBC, aux param\u00E8tres de s\u00E9curit\u00E9 AWS ou au processus de r\u00E9cup\u00E9ration de la source de donn\u00E9es AWS, qui peut prendre jusqu\u2019\u00E0 2 minutes.
aws.exception.datasource.recovery.instance.not.active=L\u2019instance de la source de donn\u00E9es AWS n\u2019est pas active.
aws.exception.datasource.recovery.is.not.possible=La source de donn\u00E9es AWS ne peut pas \u00EAtre r\u00E9cup\u00E9r\u00E9e automatiquement car votre JasperReports Server et instance de base de donn\u00E9es ne se trouvent pas dans le m\u00EAme VPC.
aws.exception.datasource.recovery.public.ip.not.provided=Vous devez indiquer l\u2019adresse IP publique d\u2019entr\u00E9e de ce serveur dans les param\u00E8tres de cloud pour pouvoir utiliser la configuration et la r\u00E9cup\u00E9ration automatis\u00E9es de la source de donn\u00E9es AWS.
aws.exception.datasource.recovery.public.ip.not.determined=Impossible de d\u00E9terminer l\u2019adresse IP d\u2019instance pour la r\u00E9cup\u00E9ration de la source de donn\u00E9es AWS.
aws.exception.datasource.load.default.credentials=Cette instance ne peut pas utiliser les <b>informations d'identification d'instance EC2</b> pour se connecter automatiquement \u00E0 Amazon RDS et Amazon Redshift, car aucun r\u00F4le de gestion des identit\u00E9s et des acc\u00E8s (IAM) n'y a \u00E9t\u00E9 affect\u00E9. Pour d\u00E9couvrir comment lancer un serveur capable de se connecter automatiquement aux sources de donn\u00E9es AWS en toute s\u00E9curit\u00E9, veuillez lire la section <a class='launcher inline' href='http://community.jaspersoft.com/jaspersoft-aws/launch' target='_blank'>Lancement de Jaspersoft pour AWS</a> t<br><br>Sinon, vous pouvez utiliser les <b>informations d'identification AWS</b>.
aws.exception.datasource.rds.vpc.recovery=Impossible d\u2019attribuer automatiquement le groupe de s\u00E9curit\u00E9 VPC nomm\u00E9 {0} \u00E0 l\u2019instance RDS {1}. L\u2019op\u00E9ration n\u2019est actuellement pas prise en charge par l\u2019API AWS. Attribuez manuellement le groupe de s\u00E9curit\u00E9 \u00E0 votre instance RDS.
aws.exception.datasource.accessKey.invalid=La cl\u00E9 d\u2019acc\u00E8s AWS n\u2019est pas valide.
aws.exception.datasource.secretKey.invalid=La cl\u00E9 secr\u00E8te AWS n\u2019est pas valide.

#AZURE data source specific exception messages
azure.exception.datasource.recovery.public.ip.not.provided=Vous devez indiquer l\u2019adresse IP publique d\u2019entr\u00E9e de ce serveur dans les param\u00E8tres de cloud pour pouvoir utiliser la configuration et la r\u00E9cup\u00E9ration automatis\u00E9es de la source de donn\u00E9es Azure.
azure.exception.datasource.recovery.firewall.rule.name.not.provided=Vous devez indiquer le nom de r\u00E8gle de pare-feu de ce serveur dans les param\u00E8tres de cloud pour pouvoir utiliser la configuration et la r\u00E9cup\u00E9ration automatis\u00E9es de la source de donn\u00E9es Azure.
azure.exception.datasource.recovery.server.name.not.provided=Vous devez indiquer le nom de ce serveur pour pouvoir utiliser la configuration et la r\u00E9cup\u00E9ration automatis\u00E9es de la source de donn\u00E9es Azure.
azure.exception.datasource.recovery.subscription.id.not.provided=Vous devez indiquer l\u2019ID d\u2019abonnement pour pouvoir utiliser la configuration et la r\u00E9cup\u00E9ration automatis\u00E9es de la source de donn\u00E9es Azure.
azure.exception.datasource.recovery.key.store.file.not.provided=Vous devez indiquer le fichier de magasin de cl\u00E9s pour pouvoir utiliser la configuration et la r\u00E9cup\u00E9ration automatis\u00E9es de la source de donn\u00E9es Azure.
azure.exception.datasource.recovery.key.store.type.not.provided=Vous devez indiquer le type de magasin de cl\u00E9s pour pouvoir utiliser la configuration et la r\u00E9cup\u00E9ration automatis\u00E9es de la source de donn\u00E9es Azure.
azure.exception.datasource.key.error=Erreur de lecture du fichier de certificat dans le r\u00E9f\u00E9rentiel. V\u00E9rifiez que le fichier et le mot de passe du certificat sont valides.
azure.exception.datasource.auth.error=Erreur d\u2019authentification. V\u00E9rifiez que l\u2019ID et le certificat d\u2019abonnement sont valides.
azure.exception.datasource.cannot.retrieve.database.list=Impossible de r\u00E9cup\u00E9rer des bases de donn\u00E9es de la gestion SQL.
azure.exception.datasource.cannot.ensure.firewall.rule=Impossible d\u2019activer la r\u00E8gle de pare-feu Azure.
azure.exception.datasource.cannot.recover.datasource=Impossible de r\u00E9cup\u00E9rer une source de donn\u00E9es Azure.

#Cluster specific exception messages
cluster.exception.session.attribute.missing=Une erreur non li\u00E9e s'est produite sur le serveur. Votre session a \u00E9t\u00E9 red\u00E9marr\u00E9e, mais tout travail non enregistr\u00E9 sera perdu. Veuillez nous excuser pour la g\u00EAne occasionn\u00E9e.<p><p>Cliquez sur le lien <a class=\"launcher inline\" href=\"home.html\">Aller \u00E0 la page d'accueil</a> pour revenir \u00E0 la page d'accueil et recommencer. Si vous rencontrez une autre erreur, veuillez contacter votre administrateur.
cluster.exception.session.attribute.missing.popup=Une erreur non li\u00E9e s'est produite sur le serveur. Votre session a \u00E9t\u00E9 red\u00E9marr\u00E9e, mais tout travail non enregistr\u00E9 sera perdu. Veuillez nous excuser pour la g\u00EAne occasionn\u00E9e.<p><p>Cliquez sur le lien ci-dessous pour revenir \u00E0 la page d'accueil et recommencer. Si vous rencontrez une autre erreur, veuillez contacter votre administrateur.

#Profile attributes substitution error and debug level messages
profile.attribute.exception.substitution.base = Il existe une erreur de substitution d\u2019attribut dans le champ \"{1}\" de la ressource \"{0}\".
profile.attribute.substitution.not.found = Le nom d\u2019attribut \"{0}\" n\u2019est pas d\u00E9fini dans le \"{1}\".
profile.attribute.substitution.not.found.in.resource = Il existe une erreur de substitution d\u2019attribut dans le champ \"{1}\" de la ressource \"{0}\". Le nom d\u2019attribut \"{2}\" n\u2019est pas d\u00E9fini dans le \"{3}\".
profile.attribute.substitution.category.invalid = Dans l\u2019attribut \"{1}\", la cat\u00E9gorie \"{0}\" n\u2019est pas valide. Elle doit provenir de \"{2}\".
profile.attribute.substitution.category.invalid.in.resource = Il existe une erreur de substitution d\u2019attribut dans le champ \"{1}\" de la ressource \"{0}\". Dans l\u2019attribut \"{3}\", la cat\u00E9gorie \"{2}\" n\u2019est pas valide. Elle doit provenir de \"{4}\".
profile.attribute.debug.substitution.success = L\u2019attribut \"{0}\" a \u00E9t\u00E9 substitu\u00E9 dans la ressource \"{1}\". Nouvelle valeur du champ \"{2}\" : \"{3}\".

#Query execution exceptions.
query.execution.not.found=L\u2019ID d\u2019ex\u00E9cution de la requ\u00EAte \"{0}\" est introuvable sur le serveur.
query.execution.cancelled=L\u2019ID d\u2019ex\u00E9cution de la requ\u00EAte \"{0}\" est annul\u00E9.
query.datasource.invalid=La source de donn\u00E9es \"{0}\" a provoqu\u00E9 une erreur lors de l\u2019ex\u00E9cution de la requ\u00EAte.
datasource.connection.failed=La connexion \u00E0 la source de donn\u00E9es a \u00E9chou\u00E9.

#Paging exceptions.
paging.offset.out.of.range = Le d\u00E9calage de ligne sp\u00E9cifi\u00E9 n\u2019est pas valide. Il doit \u00EAtre compris entre \"{0}\" et \"{1}\".
paging.page.size.out.of.range = La taille de page sp\u00E9cifi\u00E9e n\u2019est pas valide. Elle doit \u00EAtre sup\u00E9rieure \u00E0 \"{0}\".
query.limit.out.of.range = La limite de requ\u00EAte sp\u00E9cifi\u00E9e n\u2019est pas valide. Elle doit \u00EAtre comprise entre \"{0}\" et \"{1}\".
paging.axis.count.out.of.range=Le nombre d\u2019axes de page ne doit pas d\u00E9passer 1 pour les requ\u00EAtes multi-niveaux ou 2 pour les requ\u00EAtes multi-axes.

# Ad Hoc REST
query.where.parameter.not.valid=Le param\u00E8tre \"{0}\" comporte une valeur non valide \"{1}\" pour l''op\u00E9rateur \"{2}\".
query.field.ids.collision=Les ID de champ de requ\u00EAte \"{0}\" entrent en conflit avec un ID ou un nom de champ de source de donn\u00E9es existants.
query.field.ids.metadata.field.collision=Les ID de champ de requ\u00EAte \"{0}\" entrent en conflit avec un nom de champ de m\u00E9tadonn\u00E9es existant.
query.parameter.name.query.field.id.collision=Il existe un conflit entre le nom du param\u00E8tre de la requ\u00EAte \"{0}\" et un ID de champ de requ\u00EAte existant.
query.parameter.name.metadata.field.collision=Il existe un conflit entre le nom du param\u00E8tre de la requ\u00EAte \"{0}\" et le champ de m\u00E9tadonn\u00E9es.
report.missing.data.source.fields=Le rapport comporte un ou plusieurs \u00E9l\u00E9ments qui ne figurent pas dans les donn\u00E9es source. Vous devez modifier l'affichage \u00E0 la demande utilis\u00E9 pour cr\u00E9er ce rapport, puis enregistrez \u00E0 nouveau le rapport.
adhoc.missing.data.source.fields=Le rapport comporte un ou plusieurs \u00E9l\u00E9ments qui ne figurent pas dans les donn\u00E9es source. Vous devez modifier l'affichage \u00E0 la demande.
query.in.memory.datasource.type.not.supported=La valeur de \"{0}\" n\u2019est pas valide. La source de donn\u00E9es en m\u00E9moire est de type \"{1}\", non pris en charge pour l\u2019ex\u00E9cution des requ\u00EAtes.
expression.representation.required = Dans \"{0}\", un objet ou un segment d\u2019expression doit \u00EAtre sp\u00E9cifi\u00E9. Les deux repr\u00E9sentations sont toutefois nulles.
query.datasource.not.found=L\u2019URI de la source de donn\u00E9es \"{0}\" est introuvable sur le serveur.
query.datasource.access.denied=Vous n\u2019\u00EAtes pas autoris\u00E9 \u00E0 acc\u00E9der \u00E0 la source de donn\u00E9es \"{0}\".
query.aggregate.definition.error=La d\u00E9finition agr\u00E9g\u00E9e ne peut avoir \u00E0 la fois une expression et une fonction agr\u00E9g\u00E9e.
query.fields.from.multiple.dataislands=Les champs de requ\u00EAte \"{0}\" et \"{1}\" se trouvent dans des \u00EElots de donn\u00E9es distincts et ne peuvent pas \u00EAtre trait\u00E9s ensemble.
query.datasource.type.not.supported=La source de donn\u00E9es \"{0}\" est d\u2019un type non pris en charge pour l\u2019ex\u00E9cution de requ\u00EAtes.
query.datasource.olap.view.not.supported=La source de donn\u00E9es \"{0}\" est bas\u00E9e sur un affichage OLAP, qui n\u2019est pas pris en charge pour l\u2019ex\u00E9cution des requ\u00EAtes.
query.where.expression.type.not.supported=L\u2019expression de requ\u00EAte WHERE de type \"{0}\" n\u2019est pas prise en charge.
query.expression.not.valid=L\u2019expression de requ\u00EAte n\u2019est pas valide.
query.aggregate.expression.not.valid=L\u2019expression d\u2019agr\u00E9gation \"{1}\" du champ agr\u00E9g\u00E9 \"{0}\" n\u2019est pas valide.
query.aggregation.expression.not.valid=L\u2019expression d\u2019agr\u00E9gation de requ\u00EAte n\u2019est pas valide.

query.select.illegal.fields.state=La s\u00E9lection simultan\u00E9e de champs et de distinctFields n'est pas autoris\u00E9e

query.aggregation.function.name.not.valid=Le nom de la fonction d\u2019agr\u00E9gation \"{1}\" dans le champ agr\u00E9g\u00E9 \"{0}\" n\u2019est pas reconnu.
query.groupBy.allGroup.not.first=Dans les groupes de requ\u00EAte \"{0}\", \"allGroup\" doit \u00EAtre en premi\u00E8re position.
query.groupBy.categorizer.not.valid=La cat\u00E9gorie GROUP BY \"{0}\" n\u2019a pas de nom valide.
query.multiAxis.aggregation.is.empty=Le tableau d\u2019agr\u00E9gation d\u2019une requ\u00EAte multi-axes ne peut pas \u00EAtre vide.
query.orderBy.topOrBottom.limit.not.valid=La limite ORDER BY \"{0}\" est associ\u00E9 \u00E0 la valeur \"{1}\", mais ne doit pas \u00EAtre inf\u00E9rieure \u00E0 1.
query.orderBy.level.reference.not.valid=Le niveau de requ\u00EAte ORDER BY \"{0}\" ne peut pas \u00EAtre r\u00E9solu. La balise d\u2019agr\u00E9gation est manquante ou le fieldRef n\u2019est pas valide.

query.where.parameters.expression.not.valid=Les expressions de param\u00E8tre dans la clause WHERE ne sont pas valides ou pas prises en charge.
query.where.parameters.expression.type.not.valid=Le param\u00E8tre \"{0}\" de l\u2019expression WHERE n\u2019est pas valide pour l\u2019op\u00E9rateur \"{1}\". Il doit \u00EAtre associ\u00E9 \u00E0 l\u2019un des types suivants : \"{2}\"
query.details.unsupported=Les requ\u00EAtes multi-axes ne prennent pas en charge les d\u00E9tails. L\u2019expression SELECT ne peut pas d\u00E9finir de champs.
query.invalid.structure=La requ\u00EAte doit comprendre au moins une clause qui n\u2019est pas vide, qu\u2019il s\u2019agisse de l\u2019expression SELECT ou GROUP BY.
query.transformation.topn.not.allowed.aggregations.in.rows=Les filtres N sup\u00E9rieurs ou inf\u00E9rieurs ne sont pas autoris\u00E9s lorsqu\u2019une requ\u00EAte multi-axes comprend des agr\u00E9gations organis\u00E9es par ligne.
attribute.patterns.contains.invalid = La liste des motifs d\u2019attributs contient un motif non valide : {0}. Elle ne comprend par le(s) groupe(s) de capture de nom suivant(s) : {1}

query.expression.operands.size.out.of.bound=La taille des op\u00E9randes des expressions de requ\u00EAte \"{0}\" doit \u00EAtre comprise entre \"{1}\" et \"{2}\".
query.expansion.level.reference.not.valid = Le niveau d\u2019expansion de requ\u00EAte \"{0}\" ne peut pas \u00EAtre r\u00E9solu.
query.metadata.fields.not.found = Les champs de requ\u00EAte \"{0}\" n\u2019existent pas dans la source de donn\u00E9es.